/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { WoopSocialError } from "./woop-social-error.js";

export type CreatePostErrorResponseData = {
  code: models.CreatePostErrorCode;
  message: string;
  /**
   * Field-level validation failures. Omitted when not applicable.
   */
  validationErrors?: Array<models.ValidationError> | undefined;
  /**
   * Two social account IDs that belong to different projects.
   *
   * @remarks
   *
   * Returned when `code` is
   * `SOCIAL_ACCOUNTS_MUST_BELONG_TO_SAME_PROJECT`.
   */
  conflictingSocialAccountIds?: Array<string> | undefined;
};

export class CreatePostErrorResponse extends WoopSocialError {
  code: models.CreatePostErrorCode;
  /**
   * Field-level validation failures. Omitted when not applicable.
   */
  validationErrors?: Array<models.ValidationError> | undefined;
  /**
   * Two social account IDs that belong to different projects.
   *
   * @remarks
   *
   * Returned when `code` is
   * `SOCIAL_ACCOUNTS_MUST_BELONG_TO_SAME_PROJECT`.
   */
  conflictingSocialAccountIds?: Array<string> | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreatePostErrorResponseData;

  constructor(
    err: CreatePostErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.validationErrors != null) {
      this.validationErrors = err.validationErrors;
    }
    if (err.conflictingSocialAccountIds != null) {
      this.conflictingSocialAccountIds = err.conflictingSocialAccountIds;
    }

    this.name = "CreatePostErrorResponse";
  }
}

/** @internal */
export const CreatePostErrorResponse$inboundSchema: z.ZodMiniType<
  CreatePostErrorResponse,
  unknown
> = z.pipe(
  z.object({
    code: models.CreatePostErrorCode$inboundSchema,
    message: types.string(),
    validationErrors: types.optional(
      z.array(models.ValidationError$inboundSchema),
    ),
    conflictingSocialAccountIds: types.optional(z.array(types.string())),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreatePostErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
