/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { WoopSocialError } from "./woop-social-error.js";

export type DeletePostErrorResponseData = {
  code: models.DeletePostErrorCode;
  message: string;
};

export class DeletePostErrorResponse extends WoopSocialError {
  code: models.DeletePostErrorCode;

  /** The original data that was passed to this error instance. */
  data$: DeletePostErrorResponseData;

  constructor(
    err: DeletePostErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "DeletePostErrorResponse";
  }
}

/** @internal */
export const DeletePostErrorResponse$inboundSchema: z.ZodMiniType<
  DeletePostErrorResponse,
  unknown
> = z.pipe(
  z.object({
    code: models.DeletePostErrorCode$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new DeletePostErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
