/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthGetHealth } from "../funcs/health-get-health.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Health check
   *
   * @remarks
   * Returns a minimal response proving the WoopSocial API is reachable.
   */
  async getHealth(
    options?: RequestOptions,
  ): Promise<models.HealthResponse> {
    return unwrapAsync(healthGetHealth(
      this,
      options,
    ));
  }
}
