/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mediaCompleteUploadSession } from "../funcs/media-complete-upload-session.js";
import { mediaCreateMedia } from "../funcs/media-create-media.js";
import { mediaCreateUploadSession } from "../funcs/media-create-upload-session.js";
import { mediaGetUploadSession } from "../funcs/media-get-upload-session.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Media extends ClientSDK {
  /**
   * Upload media
   *
   * @remarks
   * Uploads a media file in a single request and creates a media item.
   *
   * The server determines the media MIME type from the uploaded file.
   *
   * Use this endpoint for straightforward uploads up to 600 MB.
   *
   * For larger files, or when you need presigned part URLs, use the upload
   * session flow under `/media/upload-sessions`.
   */
  async createMedia(
    request: operations.CreateMediaRequest,
    options?: RequestOptions,
  ): Promise<models.CreateMediaResponse> {
    return unwrapAsync(mediaCreateMedia(
      this,
      request,
      options,
    ));
  }

  /**
   * Start media upload session
   *
   * @remarks
   * Creates an upload session and returns presigned URLs for uploading the file in parts.
   *
   * This flow is intended for larger files where a single-request upload via the simpler `/media` endpoint is less practical.
   *
   * Upload the file in `partCount` parts, using the matching
   * `parts[n].uploadUrl` for each part number.
   *
   * Every part except the last must be exactly `partSizeInBytes` bytes. The
   * last part may be smaller. After all parts have been uploaded, call
   * `/media/upload-sessions/{uploadSessionId}/complete` to finalize the upload
   * and create the media item.
   */
  async createUploadSession(
    request: models.CreateUploadSessionRequest,
    options?: RequestOptions,
  ): Promise<models.UploadSession> {
    return unwrapAsync(mediaCreateUploadSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Get media upload session status
   */
  async getUploadSession(
    request: operations.GetUploadSessionRequest,
    options?: RequestOptions,
  ): Promise<models.UploadSessionStatus> {
    return unwrapAsync(mediaGetUploadSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Complete media upload session
   */
  async completeUploadSession(
    request: operations.CompleteUploadSessionRequest,
    options?: RequestOptions,
  ): Promise<models.UploadSessionStatus> {
    return unwrapAsync(mediaCompleteUploadSession(
      this,
      request,
      options,
    ));
  }
}
