/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postsCreatePosts } from "../funcs/posts-create-posts.js";
import { postsDeletePosts } from "../funcs/posts-delete-posts.js";
import { postsListPosts } from "../funcs/posts-list-posts.js";
import { postsUpdatePosts } from "../funcs/posts-update-posts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Posts extends ClientSDK {
  /**
   * List posts
   *
   * @remarks
   * Returns outbound posts that were scheduled within various projects.
   */
  async listPosts(
    request?: models.ListPostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListPostsResponse> {
    return unwrapAsync(postsListPosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete posts
   *
   * @remarks
   * Deletes one or more scheduled posts by post ID.
   *
   * Only posts with `deliveryStatus` `NOT_STARTED` can be deleted.
   *
   * Results are returned in the same order as the provided `ids`.
   */
  async deletePosts(
    request: Array<string>,
    options?: RequestOptions,
  ): Promise<models.DeletePostsResponse> {
    return unwrapAsync(postsDeletePosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Create posts
   *
   * @remarks
   * Creates one or more scheduled posts.
   *
   * Each item in the request body creates one scheduled post for a single connected social account. Each item must target a specific project.
   *
   * Each item must provide an `idempotencyKey`. Reusing the same `idempotencyKey` for the same API key replays the original result for that item. This is to help you prevent accidentally publishing the same post multiple times, in case you need to retry due to network failures.
   *
   * Results are returned in the same order as the input array.
   */
  async createPosts(
    request: Array<models.CreatePostItem>,
    options?: RequestOptions,
  ): Promise<models.CreatePostsResponse> {
    return unwrapAsync(postsCreatePosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Update posts
   *
   * @remarks
   * Updates one or more scheduled posts by post ID.
   *
   * Only posts with `deliveryStatus` `NOT_STARTED` can be updated. It performs a full replacement of the specified posts, so omitted properties are cleared.
   *
   * Results are returned in the same order as the input array.
   */
  async updatePosts(
    request: Array<models.UpdatePostItem>,
    options?: RequestOptions,
  ): Promise<models.UpdatePostsResponse> {
    return unwrapAsync(postsUpdatePosts(
      this,
      request,
      options,
    ));
  }
}
