/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postsCreatePost } from "../funcs/posts-create-post.js";
import { postsDeletePost } from "../funcs/posts-delete-post.js";
import { postsGetPost } from "../funcs/posts-get-post.js";
import { postsListSocialAccountPosts } from "../funcs/posts-list-social-account-posts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Posts extends ClientSDK {
  /**
   * Create post
   *
   * @remarks
   * Creates one post resource with one or more social-account targets.
   *
   * All referenced social accounts must belong to the same project.
   *
   * The request is validated atomically. If any social-account target fails
   * validation, the post is not created.
   */
  async createPost(
    request: models.CreatePostRequest,
    options?: RequestOptions,
  ): Promise<models.Post> {
    return unwrapAsync(postsCreatePost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get post
   *
   * @remarks
   * Returns one post with its social account posts inline.
   */
  async getPost(
    request: operations.GetPostRequest,
    options?: RequestOptions,
  ): Promise<models.Post> {
    return unwrapAsync(postsGetPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete post
   *
   * @remarks
   * Deletes one scheduled post by post ID.
   *
   * A post can only be deleted when all of its social-account deliveries are
   * still `NOT_STARTED`.
   */
  async deletePost(
    request: operations.DeletePostRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(postsDeletePost(
      this,
      request,
      options,
    ));
  }

  /**
   * List social account posts
   *
   * @remarks
   * Returns standalone social account posts for the API key's organization.
   *
   * Each item includes the materialized content and schedule for that
   * social-account target.
   */
  async listSocialAccountPosts(
    request?: operations.ListSocialAccountPostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSocialAccountPostsResponse> {
    return unwrapAsync(postsListSocialAccountPosts(
      this,
      request,
      options,
    ));
  }
}
