/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsListProjects } from "../funcs/projects-list-projects.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List projects
   *
   * @remarks
   * Returns projects that belong to the same organization as the API key. A project corresponds to a "Business Profile" in the UI.
   */
  async listProjects(
    options?: RequestOptions,
  ): Promise<Array<models.Project>> {
    return unwrapAsync(projectsListProjects(
      this,
      options,
    ));
  }
}
