/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Health } from "./health.js";
import { Media } from "./media.js";
import { Posts } from "./posts.js";
import { Projects } from "./projects.js";
import { SocialAccounts } from "./social-accounts.js";
import { Webhooks } from "./webhooks.js";

export class WoopSocial extends ClientSDK {
  private _posts?: Posts;
  get posts(): Posts {
    return (this._posts ??= new Posts(this._options));
  }

  private _projects?: Projects;
  get projects(): Projects {
    return (this._projects ??= new Projects(this._options));
  }

  private _socialAccounts?: SocialAccounts;
  get socialAccounts(): SocialAccounts {
    return (this._socialAccounts ??= new SocialAccounts(this._options));
  }

  private _media?: Media;
  get media(): Media {
    return (this._media ??= new Media(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }
}
