/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { socialAccountsCreateOAuthAuthorization } from "../funcs/social-accounts-create-o-auth-authorization.js";
import { socialAccountsGetSocialAccountPlatformInputs } from "../funcs/social-accounts-get-social-account-platform-inputs.js";
import { socialAccountsListSocialAccounts } from "../funcs/social-accounts-list-social-accounts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SocialAccounts extends ClientSDK {
  /**
   * Generate OAuth URL
   *
   * @remarks
   * Generates a browser authorization URL for connecting a new social account to a project. Open the returned `url` in a browser to complete the platform-specific OAuth flow.
   */
  async createOAuthAuthorization(
    request: models.CreateOAuthAuthorizationRequest,
    options?: RequestOptions,
  ): Promise<models.CreateOAuthAuthorizationResponse> {
    return unwrapAsync(socialAccountsCreateOAuthAuthorization(
      this,
      request,
      options,
    ));
  }

  /**
   * List social accounts
   *
   * @remarks
   * Returns social accounts that can currently be used for publishing.
   *
   * When `projectId` is provided, only social accounts usable within that project are returned.
   */
  async listSocialAccounts(
    request?: operations.ListSocialAccountsRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.SocialAccount>> {
    return unwrapAsync(socialAccountsListSocialAccounts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get platform-specific input options
   *
   * @remarks
   * Returns platform-specific input options for a connected social account.
   *
   * Use this endpoint to discover valid values for fields inside `platformSpecifics` when creating posts for Pinterest and TikTok.
   */
  async getSocialAccountPlatformInputs(
    request: operations.GetSocialAccountPlatformInputsRequest,
    options?: RequestOptions,
  ): Promise<models.SocialAccountPlatformInputs> {
    return unwrapAsync(socialAccountsGetSocialAccountPlatformInputs(
      this,
      request,
      options,
    ));
  }
}
