/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreateWebhookEndpoint } from "../funcs/webhooks-create-webhook-endpoint.js";
import { webhooksDeleteWebhookEndpoint } from "../funcs/webhooks-delete-webhook-endpoint.js";
import { webhooksListWebhookEndpoints } from "../funcs/webhooks-list-webhook-endpoints.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * Register webhook endpoint
   *
   * @remarks
   * Registers a URL to receive webhook events for the specified event types.
   *
   * The response includes a `signingSecret` (base64-encoded, 32 bytes) that is
   * returned **once only**. Use it to verify the `X-Woop-Signature` header on
   * incoming webhook payloads.
   *
   * **Signature format:** `t=<unix>,v1=<hmac-sha256-hex>`
   * **Signed payload:** `<unix>.<json-body>`
   */
  async createWebhookEndpoint(
    request: models.CreateWebhookEndpointRequest,
    options?: RequestOptions,
  ): Promise<models.WebhookEndpoint> {
    return unwrapAsync(webhooksCreateWebhookEndpoint(
      this,
      request,
      options,
    ));
  }

  /**
   * List webhook endpoints
   *
   * @remarks
   * Returns all registered webhook endpoints for the organization. The `signingSecret` field is omitted.
   */
  async listWebhookEndpoints(
    options?: RequestOptions,
  ): Promise<Array<models.WebhookEndpoint>> {
    return unwrapAsync(webhooksListWebhookEndpoints(
      this,
      options,
    ));
  }

  /**
   * Delete webhook endpoint
   */
  async deleteWebhookEndpoint(
    request: operations.DeleteWebhookEndpointRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksDeleteWebhookEndpoint(
      this,
      request,
      options,
    ));
  }
}
