/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the woopsocial SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx postsListPosts.example.ts
 */

import { WoopSocial } from "woopsocial";

const woopSocial = new WoopSocial({
  bearerAuth: process.env["WOOPSOCIAL_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await woopSocial.posts.listPosts();

  console.log(result);
}

main().catch(console.error);
