/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CompleteUploadSessionRequest = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
};

/** @internal */
export type CompleteUploadSessionRequest$Outbound = {
  uploadSessionId: string;
};

/** @internal */
export const CompleteUploadSessionRequest$outboundSchema: z.ZodMiniType<
  CompleteUploadSessionRequest$Outbound,
  CompleteUploadSessionRequest
> = z.object({
  uploadSessionId: z.string(),
});

export function completeUploadSessionRequestToJSON(
  completeUploadSessionRequest: CompleteUploadSessionRequest,
): string {
  return JSON.stringify(
    CompleteUploadSessionRequest$outboundSchema.parse(
      completeUploadSessionRequest,
    ),
  );
}
