/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateMediaRequest = {
  /**
   * Project that will own the uploaded media.
   */
  projectId: string;
  body: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export type CreateMediaRequest$Outbound = {
  projectId: string;
  body: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateMediaRequest$outboundSchema: z.ZodMiniType<
  CreateMediaRequest$Outbound,
  CreateMediaRequest
> = z.object({
  projectId: z.string(),
  body: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function createMediaRequestToJSON(
  createMediaRequest: CreateMediaRequest,
): string {
  return JSON.stringify(
    CreateMediaRequest$outboundSchema.parse(createMediaRequest),
  );
}
