/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeletePostRequest = {
  /**
   * Post identifier.
   */
  postId: string;
};

/** @internal */
export type DeletePostRequest$Outbound = {
  postId: string;
};

/** @internal */
export const DeletePostRequest$outboundSchema: z.ZodMiniType<
  DeletePostRequest$Outbound,
  DeletePostRequest
> = z.object({
  postId: z.string(),
});

export function deletePostRequestToJSON(
  deletePostRequest: DeletePostRequest,
): string {
  return JSON.stringify(
    DeletePostRequest$outboundSchema.parse(deletePostRequest),
  );
}
