/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetUploadSessionRequest = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
};

/** @internal */
export type GetUploadSessionRequest$Outbound = {
  uploadSessionId: string;
};

/** @internal */
export const GetUploadSessionRequest$outboundSchema: z.ZodMiniType<
  GetUploadSessionRequest$Outbound,
  GetUploadSessionRequest
> = z.object({
  uploadSessionId: z.string(),
});

export function getUploadSessionRequestToJSON(
  getUploadSessionRequest: GetUploadSessionRequest,
): string {
  return JSON.stringify(
    GetUploadSessionRequest$outboundSchema.parse(getUploadSessionRequest),
  );
}
