/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetPostRequest = {
  /**
   * Post identifier.
   */
  postId: string;
};

/** @internal */
export type GetPostRequest$Outbound = {
  postId: string;
};

/** @internal */
export const GetPostRequest$outboundSchema: z.ZodMiniType<
  GetPostRequest$Outbound,
  GetPostRequest
> = z.object({
  postId: z.string(),
});

export function getPostRequestToJSON(getPostRequest: GetPostRequest): string {
  return JSON.stringify(GetPostRequest$outboundSchema.parse(getPostRequest));
}
