/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSocialAccountPlatformInputsRequest = {
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
};

/** @internal */
export type GetSocialAccountPlatformInputsRequest$Outbound = {
  socialAccountId: string;
};

/** @internal */
export const GetSocialAccountPlatformInputsRequest$outboundSchema:
  z.ZodMiniType<
    GetSocialAccountPlatformInputsRequest$Outbound,
    GetSocialAccountPlatformInputsRequest
  > = z.object({
    socialAccountId: z.string(),
  });

export function getSocialAccountPlatformInputsRequestToJSON(
  getSocialAccountPlatformInputsRequest: GetSocialAccountPlatformInputsRequest,
): string {
  return JSON.stringify(
    GetSocialAccountPlatformInputsRequest$outboundSchema.parse(
      getSocialAccountPlatformInputsRequest,
    ),
  );
}
