/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListSocialAccountsRequest = {
  /**
   * Filter to resources that belong to a specific project.
   */
  projectId?: string | undefined;
};

/** @internal */
export type ListSocialAccountsRequest$Outbound = {
  projectId?: string | undefined;
};

/** @internal */
export const ListSocialAccountsRequest$outboundSchema: z.ZodMiniType<
  ListSocialAccountsRequest$Outbound,
  ListSocialAccountsRequest
> = z.object({
  projectId: z.optional(z.string()),
});

export function listSocialAccountsRequestToJSON(
  listSocialAccountsRequest: ListSocialAccountsRequest,
): string {
  return JSON.stringify(
    ListSocialAccountsRequest$outboundSchema.parse(listSocialAccountsRequest),
  );
}
