/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type ListSocialAccountPostsRequest = {
  /**
   * Filter to one or more projects. Provide a comma-separated list of project IDs.
   */
  projectId?: Array<string> | undefined;
  /**
   * Filter to one or more connected social accounts. Provide a comma-separated list of social account IDs.
   */
  socialAccountId?: Array<string> | undefined;
  /**
   * Filter to one or more parent posts. Provide a comma-separated list of post IDs.
   */
  postId?: Array<string> | undefined;
  /**
   * Filter to one or more social platforms. Provide a comma-separated list of platform values.
   */
  platform?: Array<models.SocialPlatform> | undefined;
  /**
   * Filter to one or more delivery statuses. Provide a comma-separated list of delivery status values.
   */
  deliveryStatus?: Array<models.DeliveryStatus> | undefined;
  /**
   * Number of items to return.
   */
  limit?: number | undefined;
  /**
   * Opaque cursor for the next page of results.
   */
  cursor?: string | undefined;
};

/** @internal */
export type ListSocialAccountPostsRequest$Outbound = {
  projectId?: Array<string> | undefined;
  socialAccountId?: Array<string> | undefined;
  postId?: Array<string> | undefined;
  platform?: Array<string> | undefined;
  deliveryStatus?: Array<string> | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListSocialAccountPostsRequest$outboundSchema: z.ZodMiniType<
  ListSocialAccountPostsRequest$Outbound,
  ListSocialAccountPostsRequest
> = z.object({
  projectId: z.optional(z.array(z.string())),
  socialAccountId: z.optional(z.array(z.string())),
  postId: z.optional(z.array(z.string())),
  platform: z.optional(z.array(models.SocialPlatform$outboundSchema)),
  deliveryStatus: z.optional(z.array(models.DeliveryStatus$outboundSchema)),
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
});

export function listSocialAccountPostsRequestToJSON(
  listSocialAccountPostsRequest: ListSocialAccountPostsRequest,
): string {
  return JSON.stringify(
    ListSocialAccountPostsRequest$outboundSchema.parse(
      listSocialAccountPostsRequest,
    ),
  );
}
