/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const CreatePostErrorCode = {
  InvalidSocialAccountId: "INVALID_SOCIAL_ACCOUNT_ID",
  SocialAccountNotConnected: "SOCIAL_ACCOUNT_NOT_CONNECTED",
  SocialAccountsMustBelongToSameProject:
    "SOCIAL_ACCOUNTS_MUST_BELONG_TO_SAME_PROJECT",
  DuplicateSocialAccountId: "DUPLICATE_SOCIAL_ACCOUNT_ID",
  InvalidMediaId: "INVALID_MEDIA_ID",
  InvalidPlatformSpecificData: "INVALID_PLATFORM_SPECIFIC_DATA",
  ValidationFailed: "VALIDATION_FAILED",
  InternalError: "INTERNAL_ERROR",
} as const;
export type CreatePostErrorCode = OpenEnum<typeof CreatePostErrorCode>;

/** @internal */
export const CreatePostErrorCode$inboundSchema: z.ZodMiniType<
  CreatePostErrorCode,
  unknown
> = openEnums.inboundSchema(CreatePostErrorCode);
