/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateUploadSessionRequest = {
  /**
   * Project that will own the uploaded media.
   */
  projectId: string;
  /**
   * Total size of the file that will be uploaded.
   */
  fileSizeInBytes: number;
};

/** @internal */
export type CreateUploadSessionRequest$Outbound = {
  projectId: string;
  fileSizeInBytes: number;
};

/** @internal */
export const CreateUploadSessionRequest$outboundSchema: z.ZodMiniType<
  CreateUploadSessionRequest$Outbound,
  CreateUploadSessionRequest
> = z.object({
  projectId: z.string(),
  fileSizeInBytes: z.int(),
});

export function createUploadSessionRequestToJSON(
  createUploadSessionRequest: CreateUploadSessionRequest,
): string {
  return JSON.stringify(
    CreateUploadSessionRequest$outboundSchema.parse(createUploadSessionRequest),
  );
}
