/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CreatePostResult,
  CreatePostResult$inboundSchema,
} from "./create-post-result.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CreatePostsResponse = {
  /**
   * Results in the same order as the request items.
   */
  results: Array<CreatePostResult>;
};

/** @internal */
export const CreatePostsResponse$inboundSchema: z.ZodMiniType<
  CreatePostsResponse,
  unknown
> = z.object({
  results: z.array(CreatePostResult$inboundSchema),
});

export function createPostsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePostsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePostsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePostsResponse' from JSON`,
  );
}
