/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PlatformSpecifics,
  PlatformSpecifics$Outbound,
  PlatformSpecifics$outboundSchema,
} from "./platform-specifics.js";

export type CreatePostItem = {
  /**
   * Client-provided item idempotency key.
   */
  idempotencyKey: string;
  /**
   * Project identifier.
   */
  projectId: string;
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * UTC time when this post should be published.
   */
  scheduledForUTC: Date;
  title?: string | undefined;
  description?: string | undefined;
  firstComment?: string | undefined;
  /**
   * Media identifiers previously created via the external media upload flow.
   */
  mediaIds?: Array<string> | undefined;
  /**
   * Platform-specific publishing options. The `platform` value must match the publishing account's platform.
   */
  platformSpecifics: PlatformSpecifics;
};

/** @internal */
export type CreatePostItem$Outbound = {
  idempotencyKey: string;
  projectId: string;
  socialAccountId: string;
  scheduledForUTC: string;
  title?: string | undefined;
  description?: string | undefined;
  firstComment?: string | undefined;
  mediaIds?: Array<string> | undefined;
  platformSpecifics: PlatformSpecifics$Outbound;
};

/** @internal */
export const CreatePostItem$outboundSchema: z.ZodMiniType<
  CreatePostItem$Outbound,
  CreatePostItem
> = z.object({
  idempotencyKey: z.string(),
  projectId: z.string(),
  socialAccountId: z.string(),
  scheduledForUTC: z.pipe(z.date(), z.transform(v => v.toISOString())),
  title: z.optional(z.string()),
  description: z.optional(z.string()),
  firstComment: z.optional(z.string()),
  mediaIds: z.optional(z.array(z.string())),
  platformSpecifics: PlatformSpecifics$outboundSchema,
});

export function createPostItemToJSON(createPostItem: CreatePostItem): string {
  return JSON.stringify(CreatePostItem$outboundSchema.parse(createPostItem));
}
