/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";
import {
  PostSchedule,
  PostSchedule$Outbound,
  PostSchedule$outboundSchema,
} from "./post-schedule.js";
import {
  SocialAccountTargetInput,
  SocialAccountTargetInput$Outbound,
  SocialAccountTargetInput$outboundSchema,
} from "./social-account-target-input.js";

export type CreatePostRequest = {
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  content: Array<PostContentItemInput>;
  schedule: PostSchedule;
  /**
   * Social-account targets for this post.
   *
   * @remarks
   *
   * All referenced social accounts must belong to the same project.
   * Duplicate `socialAccountId` values are invalid.
   */
  socialAccounts: Array<SocialAccountTargetInput>;
};

/** @internal */
export type CreatePostRequest$Outbound = {
  content: Array<PostContentItemInput$Outbound>;
  schedule: PostSchedule$Outbound;
  socialAccounts: Array<SocialAccountTargetInput$Outbound>;
};

/** @internal */
export const CreatePostRequest$outboundSchema: z.ZodMiniType<
  CreatePostRequest$Outbound,
  CreatePostRequest
> = z.object({
  content: z.array(PostContentItemInput$outboundSchema),
  schedule: PostSchedule$outboundSchema,
  socialAccounts: z.array(SocialAccountTargetInput$outboundSchema),
});

export function createPostRequestToJSON(
  createPostRequest: CreatePostRequest,
): string {
  return JSON.stringify(
    CreatePostRequest$outboundSchema.parse(createPostRequest),
  );
}
