/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const CreatePostFailureCode = {
  InvalidProjectId: "INVALID_PROJECT_ID",
  ProjectNotFound: "PROJECT_NOT_FOUND",
  InvalidSocialAccountId: "INVALID_SOCIAL_ACCOUNT_ID",
  SocialAccountNotConnected: "SOCIAL_ACCOUNT_NOT_CONNECTED",
  InvalidMediaId: "INVALID_MEDIA_ID",
  InvalidPlatformSpecificData: "INVALID_PLATFORM_SPECIFIC_DATA",
  ValidationFailed: "VALIDATION_FAILED",
  InternalError: "INTERNAL_ERROR",
} as const;
export type CreatePostFailureCode = OpenEnum<typeof CreatePostFailureCode>;

/** @internal */
export const CreatePostFailureCode$inboundSchema: z.ZodMiniType<
  CreatePostFailureCode,
  unknown
> = openEnums.inboundSchema(CreatePostFailureCode);
