/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CreateOAuthAuthorizationResponse = {
  /**
   * Browser URL that starts the OAuth authorization flow.
   */
  url: string;
};

/** @internal */
export const CreateOAuthAuthorizationResponse$inboundSchema: z.ZodMiniType<
  CreateOAuthAuthorizationResponse,
  unknown
> = z.object({
  url: types.string(),
});

export function createOAuthAuthorizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOAuthAuthorizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOAuthAuthorizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOAuthAuthorizationResponse' from JSON`,
  );
}
