/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  SocialPlatform,
  SocialPlatform$outboundSchema,
} from "./social-platform.js";

export type CreateOAuthAuthorizationRequest = {
  /**
   * Project identifier.
   */
  projectId: string;
  /**
   * `WOOPTEST` is a sandbox platform for testing and debugging. Posts targeting `WOOPTEST` go through the full scheduling pipeline but are never published to any real social network.
   *
   * @remarks
   */
  platform: SocialPlatform;
};

/** @internal */
export type CreateOAuthAuthorizationRequest$Outbound = {
  projectId: string;
  platform: string;
};

/** @internal */
export const CreateOAuthAuthorizationRequest$outboundSchema: z.ZodMiniType<
  CreateOAuthAuthorizationRequest$Outbound,
  CreateOAuthAuthorizationRequest
> = z.object({
  projectId: z.string(),
  platform: SocialPlatform$outboundSchema,
});

export function createOAuthAuthorizationRequestToJSON(
  createOAuthAuthorizationRequest: CreateOAuthAuthorizationRequest,
): string {
  return JSON.stringify(
    CreateOAuthAuthorizationRequest$outboundSchema.parse(
      createOAuthAuthorizationRequest,
    ),
  );
}
