/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DeletePostResult,
  DeletePostResult$inboundSchema,
} from "./delete-post-result.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeletePostsResponse = {
  /**
   * Results in the same order as the request items.
   */
  results: Array<DeletePostResult>;
};

/** @internal */
export const DeletePostsResponse$inboundSchema: z.ZodMiniType<
  DeletePostsResponse,
  unknown
> = z.object({
  results: z.array(DeletePostResult$inboundSchema),
});

export function deletePostsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeletePostsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePostsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePostsResponse' from JSON`,
  );
}
