/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DeletePostFailureCode = {
  PostNotFound: "POST_NOT_FOUND",
  PostNotDeletable: "POST_NOT_DELETABLE",
  InternalError: "INTERNAL_ERROR",
} as const;
export type DeletePostFailureCode = OpenEnum<typeof DeletePostFailureCode>;

/** @internal */
export const DeletePostFailureCode$inboundSchema: z.ZodMiniType<
  DeletePostFailureCode,
  unknown
> = openEnums.inboundSchema(DeletePostFailureCode);
