/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DeletePostErrorCode = {
  PostNotFound: "POST_NOT_FOUND",
  PostNotDeletable: "POST_NOT_DELETABLE",
  InternalError: "INTERNAL_ERROR",
} as const;
export type DeletePostErrorCode = OpenEnum<typeof DeletePostErrorCode>;

/** @internal */
export const DeletePostErrorCode$inboundSchema: z.ZodMiniType<
  DeletePostErrorCode,
  unknown
> = openEnums.inboundSchema(DeletePostErrorCode);
