/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Delivery lifecycle status for a post.
 *
 * @remarks
 *
 * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
 * `SENDING`: Delivery is currently in progress.
 * `SENT`: Delivery completed successfully.
 * `FAILED`: Delivery completed unsuccessfully.
 */
export const DeliveryStatus = {
  NotStarted: "NOT_STARTED",
  Sending: "SENDING",
  Sent: "SENT",
  Failed: "FAILED",
} as const;
/**
 * Delivery lifecycle status for a post.
 *
 * @remarks
 *
 * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
 * `SENDING`: Delivery is currently in progress.
 * `SENT`: Delivery completed successfully.
 * `FAILED`: Delivery completed unsuccessfully.
 */
export type DeliveryStatus = OpenEnum<typeof DeliveryStatus>;

/** @internal */
export const DeliveryStatus$inboundSchema: z.ZodMiniType<
  DeliveryStatus,
  unknown
> = openEnums.inboundSchema(DeliveryStatus);
/** @internal */
export const DeliveryStatus$outboundSchema: z.ZodMiniType<
  string,
  DeliveryStatus
> = openEnums.outboundSchema(DeliveryStatus);
