/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DraftPostSchedule = {
  type: "DRAFT";
};

/** @internal */
export const DraftPostSchedule$inboundSchema: z.ZodMiniType<
  DraftPostSchedule,
  unknown
> = z.object({
  type: types.literal("DRAFT"),
});
/** @internal */
export type DraftPostSchedule$Outbound = {
  type: "DRAFT";
};

/** @internal */
export const DraftPostSchedule$outboundSchema: z.ZodMiniType<
  DraftPostSchedule$Outbound,
  DraftPostSchedule
> = z.object({
  type: z.literal("DRAFT"),
});

export function draftPostScheduleToJSON(
  draftPostSchedule: DraftPostSchedule,
): string {
  return JSON.stringify(
    DraftPostSchedule$outboundSchema.parse(draftPostSchedule),
  );
}
export function draftPostScheduleFromJSON(
  jsonString: string,
): SafeParseResult<DraftPostSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DraftPostSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftPostSchedule' from JSON`,
  );
}
