/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryStatus,
  DeliveryStatus$inboundSchema,
} from "./delivery-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FacebookPostType,
  FacebookPostType$inboundSchema,
} from "./facebook-post-type.js";
import {
  PostContentItem,
  PostContentItem$inboundSchema,
} from "./post-content-item.js";

export type FacebookPost = {
  platform: "FACEBOOK";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Delivery lifecycle status for a post.
   *
   * @remarks
   *
   * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
   * `SENDING`: Delivery is currently in progress.
   * `SENT`: Delivery completed successfully.
   * `FAILED`: Delivery completed unsuccessfully.
   */
  deliveryStatus: DeliveryStatus;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is returned.
   */
  contentOverride?: Array<PostContentItem> | undefined;
  sentAt?: Date | undefined;
  externalPostId?: string | undefined;
  externalPostUrl?: string | undefined;
  errorMessage?: string | undefined;
  link?: string | undefined;
  postType: FacebookPostType;
};

/** @internal */
export const FacebookPost$inboundSchema: z.ZodMiniType<FacebookPost, unknown> =
  z.object({
    platform: types.literal("FACEBOOK"),
    socialAccountId: types.string(),
    deliveryStatus: DeliveryStatus$inboundSchema,
    contentOverride: types.optional(z.array(PostContentItem$inboundSchema)),
    sentAt: types.optional(types.date()),
    externalPostId: types.optional(types.string()),
    externalPostUrl: types.optional(types.string()),
    errorMessage: types.optional(types.string()),
    link: types.optional(types.string()),
    postType: FacebookPostType$inboundSchema,
  });

export function facebookPostFromJSON(
  jsonString: string,
): SafeParseResult<FacebookPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FacebookPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FacebookPost' from JSON`,
  );
}
