/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FacebookPostType,
  FacebookPostType$inboundSchema,
  FacebookPostType$outboundSchema,
} from "./facebook-post-type.js";

export type FacebookSpecifics = {
  platform: "FACEBOOK";
  link?: string | undefined;
  postType: FacebookPostType;
};

/** @internal */
export const FacebookSpecifics$inboundSchema: z.ZodMiniType<
  FacebookSpecifics,
  unknown
> = z.object({
  platform: types.literal("FACEBOOK"),
  link: types.optional(types.string()),
  postType: FacebookPostType$inboundSchema,
});
/** @internal */
export type FacebookSpecifics$Outbound = {
  platform: "FACEBOOK";
  link?: string | undefined;
  postType: string;
};

/** @internal */
export const FacebookSpecifics$outboundSchema: z.ZodMiniType<
  FacebookSpecifics$Outbound,
  FacebookSpecifics
> = z.object({
  platform: z.literal("FACEBOOK"),
  link: z.optional(z.string()),
  postType: FacebookPostType$outboundSchema,
});

export function facebookSpecificsToJSON(
  facebookSpecifics: FacebookSpecifics,
): string {
  return JSON.stringify(
    FacebookSpecifics$outboundSchema.parse(facebookSpecifics),
  );
}
export function facebookSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<FacebookSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FacebookSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FacebookSpecifics' from JSON`,
  );
}
