/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const FacebookPostType = {
  TextOnly: "TEXT_ONLY",
  Image: "IMAGE",
  Video: "VIDEO",
  Reel: "REEL",
} as const;
export type FacebookPostType = OpenEnum<typeof FacebookPostType>;

/** @internal */
export const FacebookPostType$inboundSchema: z.ZodMiniType<
  FacebookPostType,
  unknown
> = openEnums.inboundSchema(FacebookPostType);
/** @internal */
export const FacebookPostType$outboundSchema: z.ZodMiniType<
  string,
  FacebookPostType
> = openEnums.outboundSchema(FacebookPostType);
