/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  FacebookPostType,
  FacebookPostType$outboundSchema,
} from "./facebook-post-type.js";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";

export type FacebookInput = {
  platform: "FACEBOOK";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
  link?: string | undefined;
  postType: FacebookPostType;
};

/** @internal */
export type FacebookInput$Outbound = {
  platform: "FACEBOOK";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
  link?: string | undefined;
  postType: string;
};

/** @internal */
export const FacebookInput$outboundSchema: z.ZodMiniType<
  FacebookInput$Outbound,
  FacebookInput
> = z.object({
  platform: z.literal("FACEBOOK"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
  link: z.optional(z.string()),
  postType: FacebookPostType$outboundSchema,
});

export function facebookInputToJSON(facebookInput: FacebookInput): string {
  return JSON.stringify(FacebookInput$outboundSchema.parse(facebookInput));
}
