/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const GetPostErrorCode = {
  PostNotFound: "POST_NOT_FOUND",
  InternalError: "INTERNAL_ERROR",
} as const;
export type GetPostErrorCode = OpenEnum<typeof GetPostErrorCode>;

/** @internal */
export const GetPostErrorCode$inboundSchema: z.ZodMiniType<
  GetPostErrorCode,
  unknown
> = openEnums.inboundSchema(GetPostErrorCode);
