/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  InstagramPostType,
  InstagramPostType$inboundSchema,
  InstagramPostType$outboundSchema,
} from "./instagram-post-type.js";

export type InstagramSpecifics = {
  platform: "INSTAGRAM";
  postType: InstagramPostType;
};

/** @internal */
export const InstagramSpecifics$inboundSchema: z.ZodMiniType<
  InstagramSpecifics,
  unknown
> = z.object({
  platform: types.literal("INSTAGRAM"),
  postType: InstagramPostType$inboundSchema,
});
/** @internal */
export type InstagramSpecifics$Outbound = {
  platform: "INSTAGRAM";
  postType: string;
};

/** @internal */
export const InstagramSpecifics$outboundSchema: z.ZodMiniType<
  InstagramSpecifics$Outbound,
  InstagramSpecifics
> = z.object({
  platform: z.literal("INSTAGRAM"),
  postType: InstagramPostType$outboundSchema,
});

export function instagramSpecificsToJSON(
  instagramSpecifics: InstagramSpecifics,
): string {
  return JSON.stringify(
    InstagramSpecifics$outboundSchema.parse(instagramSpecifics),
  );
}
export function instagramSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<InstagramSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstagramSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstagramSpecifics' from JSON`,
  );
}
