/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  InstagramPostType,
  InstagramPostType$outboundSchema,
} from "./instagram-post-type.js";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";

export type InstagramInput = {
  platform: "INSTAGRAM";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
  postType: InstagramPostType;
};

/** @internal */
export type InstagramInput$Outbound = {
  platform: "INSTAGRAM";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
  postType: string;
};

/** @internal */
export const InstagramInput$outboundSchema: z.ZodMiniType<
  InstagramInput$Outbound,
  InstagramInput
> = z.object({
  platform: z.literal("INSTAGRAM"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
  postType: InstagramPostType$outboundSchema,
});

export function instagramInputToJSON(instagramInput: InstagramInput): string {
  return JSON.stringify(InstagramInput$outboundSchema.parse(instagramInput));
}
