/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const InstagramPostType = {
  Post: "POST",
  Reel: "REEL",
  Story: "STORY",
} as const;
export type InstagramPostType = OpenEnum<typeof InstagramPostType>;

/** @internal */
export const InstagramPostType$inboundSchema: z.ZodMiniType<
  InstagramPostType,
  unknown
> = openEnums.inboundSchema(InstagramPostType);
/** @internal */
export const InstagramPostType$outboundSchema: z.ZodMiniType<
  string,
  InstagramPostType
> = openEnums.outboundSchema(InstagramPostType);
