/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type LinkedInSpecifics = {
  platform: "LINKEDIN";
};

/** @internal */
export const LinkedInSpecifics$inboundSchema: z.ZodMiniType<
  LinkedInSpecifics,
  unknown
> = z.object({
  platform: types.literal("LINKEDIN"),
});
/** @internal */
export type LinkedInSpecifics$Outbound = {
  platform: "LINKEDIN";
};

/** @internal */
export const LinkedInSpecifics$outboundSchema: z.ZodMiniType<
  LinkedInSpecifics$Outbound,
  LinkedInSpecifics
> = z.object({
  platform: z.literal("LINKEDIN"),
});

export function linkedInSpecificsToJSON(
  linkedInSpecifics: LinkedInSpecifics,
): string {
  return JSON.stringify(
    LinkedInSpecifics$outboundSchema.parse(linkedInSpecifics),
  );
}
export function linkedInSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInSpecifics' from JSON`,
  );
}
