/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";

export type LinkedInPagesInput = {
  platform: "LINKEDIN_PAGES";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
};

/** @internal */
export type LinkedInPagesInput$Outbound = {
  platform: "LINKEDIN_PAGES";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
};

/** @internal */
export const LinkedInPagesInput$outboundSchema: z.ZodMiniType<
  LinkedInPagesInput$Outbound,
  LinkedInPagesInput
> = z.object({
  platform: z.literal("LINKEDIN_PAGES"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
});

export function linkedInPagesInputToJSON(
  linkedInPagesInput: LinkedInPagesInput,
): string {
  return JSON.stringify(
    LinkedInPagesInput$outboundSchema.parse(linkedInPagesInput),
  );
}
