/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type LinkedInPagesSpecifics = {
  platform: "LINKEDIN_PAGES";
};

/** @internal */
export const LinkedInPagesSpecifics$inboundSchema: z.ZodMiniType<
  LinkedInPagesSpecifics,
  unknown
> = z.object({
  platform: types.literal("LINKEDIN_PAGES"),
});
/** @internal */
export type LinkedInPagesSpecifics$Outbound = {
  platform: "LINKEDIN_PAGES";
};

/** @internal */
export const LinkedInPagesSpecifics$outboundSchema: z.ZodMiniType<
  LinkedInPagesSpecifics$Outbound,
  LinkedInPagesSpecifics
> = z.object({
  platform: z.literal("LINKEDIN_PAGES"),
});

export function linkedInPagesSpecificsToJSON(
  linkedInPagesSpecifics: LinkedInPagesSpecifics,
): string {
  return JSON.stringify(
    LinkedInPagesSpecifics$outboundSchema.parse(linkedInPagesSpecifics),
  );
}
export function linkedInPagesSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<LinkedInPagesSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedInPagesSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedInPagesSpecifics' from JSON`,
  );
}
