/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";

export type LinkedInInput = {
  platform: "LINKEDIN";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
};

/** @internal */
export type LinkedInInput$Outbound = {
  platform: "LINKEDIN";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
};

/** @internal */
export const LinkedInInput$outboundSchema: z.ZodMiniType<
  LinkedInInput$Outbound,
  LinkedInInput
> = z.object({
  platform: z.literal("LINKEDIN"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
});

export function linkedInInputToJSON(linkedInInput: LinkedInInput): string {
  return JSON.stringify(LinkedInInput$outboundSchema.parse(linkedInInput));
}
