/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DeliveryStatus,
  DeliveryStatus$outboundSchema,
} from "./delivery-status.js";

export type ListPostsRequest = {
  /**
   * Filter to resources that belong to a specific project.
   */
  projectId?: string | undefined;
  /**
   * Delivery lifecycle status for a post.
   *
   * @remarks
   *
   * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
   * `SENDING`: Delivery is currently in progress.
   * `SENT`: Delivery completed successfully.
   * `FAILED`: Delivery completed unsuccessfully.
   */
  deliveryStatus?: DeliveryStatus | undefined;
  /**
   * Number of items to return. Defaults to 50. Maximum 100.
   */
  limit?: number | undefined;
  /**
   * Opaque cursor for the next page of results.
   */
  cursor?: string | undefined;
  /**
   * Filter to specific post IDs. When provided, only posts with matching IDs are returned.
   */
  ids?: Array<string> | undefined;
};

/** @internal */
export type ListPostsRequest$Outbound = {
  projectId?: string | undefined;
  deliveryStatus?: string | undefined;
  limit: number;
  cursor?: string | undefined;
  ids?: Array<string> | undefined;
};

/** @internal */
export const ListPostsRequest$outboundSchema: z.ZodMiniType<
  ListPostsRequest$Outbound,
  ListPostsRequest
> = z.object({
  projectId: z.optional(z.string()),
  deliveryStatus: z.optional(DeliveryStatus$outboundSchema),
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
  ids: z.optional(z.array(z.string())),
});

export function listPostsRequestToJSON(
  listPostsRequest: ListPostsRequest,
): string {
  return JSON.stringify(
    ListPostsRequest$outboundSchema.parse(listPostsRequest),
  );
}
