/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Post, Post$inboundSchema } from "./post.js";

export type ListPostsResponse = {
  posts: Array<Post>;
  /**
   * Opaque cursor for the next page of results. Omitted when there are no more results.
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const ListPostsResponse$inboundSchema: z.ZodMiniType<
  ListPostsResponse,
  unknown
> = z.object({
  posts: z.array(Post$inboundSchema),
  nextCursor: types.optional(types.string()),
});

export function listPostsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPostsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPostsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPostsResponse' from JSON`,
  );
}
