/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SocialAccountPost,
  SocialAccountPost$inboundSchema,
} from "./social-account-post.js";

export type ListSocialAccountPostsResponse = {
  socialAccountPosts: Array<SocialAccountPost>;
  /**
   * Opaque cursor for the next page of results. Omitted when there are no more results.
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const ListSocialAccountPostsResponse$inboundSchema: z.ZodMiniType<
  ListSocialAccountPostsResponse,
  unknown
> = z.object({
  socialAccountPosts: z.array(SocialAccountPost$inboundSchema),
  nextCursor: types.optional(types.string()),
});

export function listSocialAccountPostsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSocialAccountPostsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSocialAccountPostsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSocialAccountPostsResponse' from JSON`,
  );
}
