/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const MediaType = {
  Image: "IMAGE",
  Video: "VIDEO",
} as const;
export type MediaType = OpenEnum<typeof MediaType>;

export type MediaLibraryPostContentMedia = {
  type: "MEDIA_LIBRARY";
  /**
   * Media identifier from the media library.
   */
  mediaId: string;
  mediaType: MediaType;
  /**
   * Canonical media URL.
   */
  url: string;
  /**
   * Thumbnail or preview URL for the media item.
   */
  thumbnailUrl: string;
};

/** @internal */
export const MediaType$inboundSchema: z.ZodMiniType<MediaType, unknown> =
  openEnums.inboundSchema(MediaType);

/** @internal */
export const MediaLibraryPostContentMedia$inboundSchema: z.ZodMiniType<
  MediaLibraryPostContentMedia,
  unknown
> = z.object({
  type: types.literal("MEDIA_LIBRARY"),
  mediaId: types.string(),
  mediaType: MediaType$inboundSchema,
  url: types.string(),
  thumbnailUrl: types.string(),
});

export function mediaLibraryPostContentMediaFromJSON(
  jsonString: string,
): SafeParseResult<MediaLibraryPostContentMedia, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaLibraryPostContentMedia$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaLibraryPostContentMedia' from JSON`,
  );
}
