/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type MediaLibraryPostContentMediaInput = {
  type: "MEDIA_LIBRARY";
  /**
   * Media identifier from the media library.
   */
  mediaId: string;
};

/** @internal */
export type MediaLibraryPostContentMediaInput$Outbound = {
  type: "MEDIA_LIBRARY";
  mediaId: string;
};

/** @internal */
export const MediaLibraryPostContentMediaInput$outboundSchema: z.ZodMiniType<
  MediaLibraryPostContentMediaInput$Outbound,
  MediaLibraryPostContentMediaInput
> = z.object({
  type: z.literal("MEDIA_LIBRARY"),
  mediaId: z.string(),
});

export function mediaLibraryPostContentMediaInputToJSON(
  mediaLibraryPostContentMediaInput: MediaLibraryPostContentMediaInput,
): string {
  return JSON.stringify(
    MediaLibraryPostContentMediaInput$outboundSchema.parse(
      mediaLibraryPostContentMediaInput,
    ),
  );
}
