/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PinterestBoardOption,
  PinterestBoardOption$inboundSchema,
} from "./pinterest-board-option.js";

export type PinterestSocialAccountPlatformSpecificInputs = {
  platform: "PINTEREST";
  /**
   * Available Pinterest boards for this account.
   *
   * @remarks
   *
   * Each `id` value can be sent as `pinterestBoardId` when creating a
   * post for a Pinterest social-account target.
   */
  boards: Array<PinterestBoardOption>;
};

/** @internal */
export const PinterestSocialAccountPlatformSpecificInputs$inboundSchema:
  z.ZodMiniType<PinterestSocialAccountPlatformSpecificInputs, unknown> = z
    .object({
      platform: types.literal("PINTEREST"),
      boards: z.array(PinterestBoardOption$inboundSchema),
    });

export function pinterestSocialAccountPlatformSpecificInputsFromJSON(
  jsonString: string,
): SafeParseResult<
  PinterestSocialAccountPlatformSpecificInputs,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PinterestSocialAccountPlatformSpecificInputs$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PinterestSocialAccountPlatformSpecificInputs' from JSON`,
  );
}
