/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PinterestBoardOption,
  PinterestBoardOption$inboundSchema,
} from "./pinterest-board-option.js";

export type PinterestAccountPlatformInputs = {
  /**
   * Available Pinterest boards for this account.
   *
   * @remarks
   *
   * Each `id` value can be sent as
   * `platformSpecifics.pinterestBoardId` when creating a post.
   */
  boards: Array<PinterestBoardOption>;
};

/** @internal */
export const PinterestAccountPlatformInputs$inboundSchema: z.ZodMiniType<
  PinterestAccountPlatformInputs,
  unknown
> = z.object({
  boards: z.array(PinterestBoardOption$inboundSchema),
});

export function pinterestAccountPlatformInputsFromJSON(
  jsonString: string,
): SafeParseResult<PinterestAccountPlatformInputs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PinterestAccountPlatformInputs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PinterestAccountPlatformInputs' from JSON`,
  );
}
