/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";

export type PinterestInput = {
  platform: "PINTEREST";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
  /**
   * Identifier of the board to pin to.
   */
  pinterestBoardId: string;
  title?: string | undefined;
};

/** @internal */
export type PinterestInput$Outbound = {
  platform: "PINTEREST";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
  pinterestBoardId: string;
  title?: string | undefined;
};

/** @internal */
export const PinterestInput$outboundSchema: z.ZodMiniType<
  PinterestInput$Outbound,
  PinterestInput
> = z.object({
  platform: z.literal("PINTEREST"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
  pinterestBoardId: z.string(),
  title: z.optional(z.string()),
});

export function pinterestInputToJSON(pinterestInput: PinterestInput): string {
  return JSON.stringify(PinterestInput$outboundSchema.parse(pinterestInput));
}
