/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PinterestAccountPlatformInputs,
  PinterestAccountPlatformInputs$inboundSchema,
} from "./pinterest-account-platform-inputs.js";

export type PinterestSocialAccountPlatformSpecificInputs = {
  platform: "PINTEREST";
  pinterest: PinterestAccountPlatformInputs;
};

/** @internal */
export const PinterestSocialAccountPlatformSpecificInputs$inboundSchema:
  z.ZodMiniType<PinterestSocialAccountPlatformSpecificInputs, unknown> = z
    .object({
      platform: types.literal("PINTEREST"),
      pinterest: PinterestAccountPlatformInputs$inboundSchema,
    });

export function pinterestSocialAccountPlatformSpecificInputsFromJSON(
  jsonString: string,
): SafeParseResult<
  PinterestSocialAccountPlatformSpecificInputs,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PinterestSocialAccountPlatformSpecificInputs$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PinterestSocialAccountPlatformSpecificInputs' from JSON`,
  );
}
