/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PinterestBoardOption = {
  /**
   * Pinterest board identifier.
   */
  id: string;
  /**
   * Human-readable Pinterest board name.
   */
  name: string;
};

/** @internal */
export const PinterestBoardOption$inboundSchema: z.ZodMiniType<
  PinterestBoardOption,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function pinterestBoardOptionFromJSON(
  jsonString: string,
): SafeParseResult<PinterestBoardOption, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PinterestBoardOption$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PinterestBoardOption' from JSON`,
  );
}
