/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PinterestSpecifics = {
  platform: "PINTEREST";
  pinterestBoardId: string;
};

/** @internal */
export const PinterestSpecifics$inboundSchema: z.ZodMiniType<
  PinterestSpecifics,
  unknown
> = z.object({
  platform: types.literal("PINTEREST"),
  pinterestBoardId: types.string(),
});
/** @internal */
export type PinterestSpecifics$Outbound = {
  platform: "PINTEREST";
  pinterestBoardId: string;
};

/** @internal */
export const PinterestSpecifics$outboundSchema: z.ZodMiniType<
  PinterestSpecifics$Outbound,
  PinterestSpecifics
> = z.object({
  platform: z.literal("PINTEREST"),
  pinterestBoardId: z.string(),
});

export function pinterestSpecificsToJSON(
  pinterestSpecifics: PinterestSpecifics,
): string {
  return JSON.stringify(
    PinterestSpecifics$outboundSchema.parse(pinterestSpecifics),
  );
}
export function pinterestSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<PinterestSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PinterestSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PinterestSpecifics' from JSON`,
  );
}
