/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FacebookSpecifics,
  FacebookSpecifics$inboundSchema,
  FacebookSpecifics$Outbound,
  FacebookSpecifics$outboundSchema,
} from "./facebook-specifics.js";
import {
  InstagramSpecifics,
  InstagramSpecifics$inboundSchema,
  InstagramSpecifics$Outbound,
  InstagramSpecifics$outboundSchema,
} from "./instagram-specifics.js";
import {
  LinkedInPagesSpecifics,
  LinkedInPagesSpecifics$inboundSchema,
  LinkedInPagesSpecifics$Outbound,
  LinkedInPagesSpecifics$outboundSchema,
} from "./linked-in-pages-specifics.js";
import {
  LinkedInSpecifics,
  LinkedInSpecifics$inboundSchema,
  LinkedInSpecifics$Outbound,
  LinkedInSpecifics$outboundSchema,
} from "./linked-in-specifics.js";
import {
  PinterestSpecifics,
  PinterestSpecifics$inboundSchema,
  PinterestSpecifics$Outbound,
  PinterestSpecifics$outboundSchema,
} from "./pinterest-specifics.js";
import {
  TikTokSpecifics,
  TikTokSpecifics$inboundSchema,
  TikTokSpecifics$Outbound,
  TikTokSpecifics$outboundSchema,
} from "./tik-tok-specifics.js";
import {
  XSpecifics,
  XSpecifics$inboundSchema,
  XSpecifics$Outbound,
  XSpecifics$outboundSchema,
} from "./x-specifics.js";
import {
  YouTubeSpecifics,
  YouTubeSpecifics$inboundSchema,
  YouTubeSpecifics$Outbound,
  YouTubeSpecifics$outboundSchema,
} from "./you-tube-specifics.js";

/**
 * Platform-specific publishing options. The `platform` value must match the publishing account's platform.
 */
export type PlatformSpecifics =
  | PinterestSpecifics
  | InstagramSpecifics
  | FacebookSpecifics
  | TikTokSpecifics
  | YouTubeSpecifics
  | XSpecifics
  | LinkedInSpecifics
  | LinkedInPagesSpecifics
  | discriminatedUnionTypes.Unknown<"platform">;

/** @internal */
export const PlatformSpecifics$inboundSchema: z.ZodMiniType<
  PlatformSpecifics,
  unknown
> = discriminatedUnion("platform", {
  PINTEREST: PinterestSpecifics$inboundSchema,
  INSTAGRAM: InstagramSpecifics$inboundSchema,
  FACEBOOK: FacebookSpecifics$inboundSchema,
  TIKTOK: TikTokSpecifics$inboundSchema,
  YOUTUBE: YouTubeSpecifics$inboundSchema,
  X: XSpecifics$inboundSchema,
  LINKEDIN: LinkedInSpecifics$inboundSchema,
  LINKEDIN_PAGES: LinkedInPagesSpecifics$inboundSchema,
});
/** @internal */
export type PlatformSpecifics$Outbound =
  | PinterestSpecifics$Outbound
  | InstagramSpecifics$Outbound
  | FacebookSpecifics$Outbound
  | TikTokSpecifics$Outbound
  | YouTubeSpecifics$Outbound
  | XSpecifics$Outbound
  | LinkedInSpecifics$Outbound
  | LinkedInPagesSpecifics$Outbound;

/** @internal */
export const PlatformSpecifics$outboundSchema: z.ZodMiniType<
  PlatformSpecifics$Outbound,
  PlatformSpecifics
> = z.union([
  PinterestSpecifics$outboundSchema,
  InstagramSpecifics$outboundSchema,
  FacebookSpecifics$outboundSchema,
  TikTokSpecifics$outboundSchema,
  YouTubeSpecifics$outboundSchema,
  XSpecifics$outboundSchema,
  LinkedInSpecifics$outboundSchema,
  LinkedInPagesSpecifics$outboundSchema,
]);

export function platformSpecificsToJSON(
  platformSpecifics: PlatformSpecifics,
): string {
  return JSON.stringify(
    PlatformSpecifics$outboundSchema.parse(platformSpecifics),
  );
}
export function platformSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<PlatformSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformSpecifics' from JSON`,
  );
}
