/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DraftPostSchedule,
  DraftPostSchedule$inboundSchema,
  DraftPostSchedule$Outbound,
  DraftPostSchedule$outboundSchema,
} from "./draft-post-schedule.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PublishNowPostSchedule,
  PublishNowPostSchedule$inboundSchema,
  PublishNowPostSchedule$Outbound,
  PublishNowPostSchedule$outboundSchema,
} from "./publish-now-post-schedule.js";
import {
  ScheduleForLaterPostSchedule,
  ScheduleForLaterPostSchedule$inboundSchema,
  ScheduleForLaterPostSchedule$Outbound,
  ScheduleForLaterPostSchedule$outboundSchema,
} from "./schedule-for-later-post-schedule.js";

export type PostSchedule =
  | DraftPostSchedule
  | PublishNowPostSchedule
  | ScheduleForLaterPostSchedule
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const PostSchedule$inboundSchema: z.ZodMiniType<PostSchedule, unknown> =
  discriminatedUnion("type", {
    DRAFT: DraftPostSchedule$inboundSchema,
    PUBLISH_NOW: PublishNowPostSchedule$inboundSchema,
    SCHEDULE_FOR_LATER: ScheduleForLaterPostSchedule$inboundSchema,
  });
/** @internal */
export type PostSchedule$Outbound =
  | DraftPostSchedule$Outbound
  | PublishNowPostSchedule$Outbound
  | ScheduleForLaterPostSchedule$Outbound;

/** @internal */
export const PostSchedule$outboundSchema: z.ZodMiniType<
  PostSchedule$Outbound,
  PostSchedule
> = z.union([
  DraftPostSchedule$outboundSchema,
  PublishNowPostSchedule$outboundSchema,
  ScheduleForLaterPostSchedule$outboundSchema,
]);

export function postScheduleToJSON(postSchedule: PostSchedule): string {
  return JSON.stringify(PostSchedule$outboundSchema.parse(postSchedule));
}
export function postScheduleFromJSON(
  jsonString: string,
): SafeParseResult<PostSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostSchedule' from JSON`,
  );
}
