/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Type = {
  Image: "IMAGE",
  Video: "VIDEO",
} as const;
export type Type = OpenEnum<typeof Type>;

export type PostMedia = {
  /**
   * Media identifier.
   */
  mediaId: string;
  type: Type;
  /**
   * Canonical media URL.
   */
  url: string;
  /**
   * Thumbnail or preview URL for the media item.
   */
  thumbnailUrl: string;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);

/** @internal */
export const PostMedia$inboundSchema: z.ZodMiniType<PostMedia, unknown> = z
  .object({
    mediaId: types.string(),
    type: Type$inboundSchema,
    url: types.string(),
    thumbnailUrl: types.string(),
  });

export function postMediaFromJSON(
  jsonString: string,
): SafeParseResult<PostMedia, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostMedia$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostMedia' from JSON`,
  );
}
