/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryStatus,
  DeliveryStatus$inboundSchema,
} from "./delivery-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PlatformSpecifics,
  PlatformSpecifics$inboundSchema,
} from "./platform-specifics.js";
import { PostMedia, PostMedia$inboundSchema } from "./post-media.js";
import {
  SocialPlatform,
  SocialPlatform$inboundSchema,
} from "./social-platform.js";

export type Post = {
  /**
   * Post identifier.
   */
  id: string;
  /**
   * Project identifier.
   */
  projectId: string;
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Social platform supported by WoopSocial.
   */
  platform: SocialPlatform;
  /**
   * Display name or username for the connected account.
   */
  username: string;
  /**
   * Delivery lifecycle status for a post.
   *
   * @remarks
   *
   * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
   * `SENDING`: Delivery is currently in progress.
   * `SENT`: Delivery completed successfully.
   * `FAILED`: Delivery completed unsuccessfully.
   */
  deliveryStatus: DeliveryStatus;
  /**
   * Effective UTC time when the post is or was scheduled to publish.
   */
  scheduledForUTC: Date;
  /**
   * UTC time when delivery completed successfully or failed.
   */
  sentAt?: Date | undefined;
  title?: string | undefined;
  description?: string | undefined;
  firstComment?: string | undefined;
  media?: Array<PostMedia> | undefined;
  /**
   * Platform-specific publishing options. The `platform` value must match the publishing account's platform.
   */
  platformSpecifics: PlatformSpecifics;
  /**
   * ID of the published post on the external social media platform.
   */
  externalPostId?: string | undefined;
  /**
   * URL of the published post on the external social media platform.
   */
  externalPostUrl?: string | undefined;
  errorMessage?: string | undefined;
};

/** @internal */
export const Post$inboundSchema: z.ZodMiniType<Post, unknown> = z.object({
  id: types.string(),
  projectId: types.string(),
  socialAccountId: types.string(),
  platform: SocialPlatform$inboundSchema,
  username: types.string(),
  deliveryStatus: DeliveryStatus$inboundSchema,
  scheduledForUTC: types.date(),
  sentAt: types.optional(types.date()),
  title: types.optional(types.string()),
  description: types.optional(types.string()),
  firstComment: types.optional(types.string()),
  media: types.optional(z.array(PostMedia$inboundSchema)),
  platformSpecifics: PlatformSpecifics$inboundSchema,
  externalPostId: types.optional(types.string()),
  externalPostUrl: types.optional(types.string()),
  errorMessage: types.optional(types.string()),
});

export function postFromJSON(
  jsonString: string,
): SafeParseResult<Post, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Post$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Post' from JSON`,
  );
}
