/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostContentItem,
  PostContentItem$inboundSchema,
} from "./post-content-item.js";
import { PostSchedule, PostSchedule$inboundSchema } from "./post-schedule.js";
import {
  SocialAccountPost,
  SocialAccountPost$inboundSchema,
} from "./social-account-post.js";

export type Post = {
  /**
   * Post identifier.
   */
  id: string;
  /**
   * Project identifier that the selected social accounts belong to.
   */
  projectId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is returned.
   */
  content: Array<PostContentItem>;
  schedule: PostSchedule;
  /**
   * Platform-specific post instances.
   */
  socialAccountPosts: Array<SocialAccountPost>;
  /**
   * UTC time when the post was created.
   */
  createdAt: Date;
  /**
   * UTC time when the post was last updated.
   */
  updatedAt: Date;
};

/** @internal */
export const Post$inboundSchema: z.ZodMiniType<Post, unknown> = z.object({
  id: types.string(),
  projectId: types.string(),
  content: z.array(PostContentItem$inboundSchema),
  schedule: PostSchedule$inboundSchema,
  socialAccountPosts: z.array(SocialAccountPost$inboundSchema),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function postFromJSON(
  jsonString: string,
): SafeParseResult<Post, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Post$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Post' from JSON`,
  );
}
