/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentMediaInput,
  PostContentMediaInput$Outbound,
  PostContentMediaInput$outboundSchema,
} from "./post-content-media-input.js";

export type PostContentItemInput = {
  /**
   * Text content for this thread item.
   */
  text?: string | undefined;
  media?: Array<PostContentMediaInput> | undefined;
};

/** @internal */
export type PostContentItemInput$Outbound = {
  text?: string | undefined;
  media?: Array<PostContentMediaInput$Outbound> | undefined;
};

/** @internal */
export const PostContentItemInput$outboundSchema: z.ZodMiniType<
  PostContentItemInput$Outbound,
  PostContentItemInput
> = z.object({
  text: z.optional(z.string()),
  media: z.optional(z.array(PostContentMediaInput$outboundSchema)),
});

export function postContentItemInputToJSON(
  postContentItemInput: PostContentItemInput,
): string {
  return JSON.stringify(
    PostContentItemInput$outboundSchema.parse(postContentItemInput),
  );
}
