/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostContentMedia,
  PostContentMedia$inboundSchema,
} from "./post-content-media.js";

export type PostContentItem = {
  /**
   * Text content for this thread item.
   */
  text?: string | undefined;
  media?: Array<PostContentMedia> | undefined;
};

/** @internal */
export const PostContentItem$inboundSchema: z.ZodMiniType<
  PostContentItem,
  unknown
> = z.object({
  text: types.optional(types.string()),
  media: types.optional(z.array(PostContentMedia$inboundSchema)),
});

export function postContentItemFromJSON(
  jsonString: string,
): SafeParseResult<PostContentItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostContentItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostContentItem' from JSON`,
  );
}
