/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MediaLibraryPostContentMedia,
  MediaLibraryPostContentMedia$inboundSchema,
} from "./media-library-post-content-media.js";

/**
 * Resolved content media.
 *
 * @remarks
 */
export type PostContentMedia = MediaLibraryPostContentMedia;

/** @internal */
export const PostContentMedia$inboundSchema: z.ZodMiniType<
  PostContentMedia,
  unknown
> = MediaLibraryPostContentMedia$inboundSchema;

export function postContentMediaFromJSON(
  jsonString: string,
): SafeParseResult<PostContentMedia, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostContentMedia$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostContentMedia' from JSON`,
  );
}
