/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  MediaLibraryPostContentMediaInput,
  MediaLibraryPostContentMediaInput$Outbound,
  MediaLibraryPostContentMediaInput$outboundSchema,
} from "./media-library-post-content-media-input.js";

/**
 * Content media reference.
 *
 * @remarks
 */
export type PostContentMediaInput = MediaLibraryPostContentMediaInput;

/** @internal */
export type PostContentMediaInput$Outbound =
  MediaLibraryPostContentMediaInput$Outbound;

/** @internal */
export const PostContentMediaInput$outboundSchema: z.ZodMiniType<
  PostContentMediaInput$Outbound,
  PostContentMediaInput
> = MediaLibraryPostContentMediaInput$outboundSchema;

export function postContentMediaInputToJSON(
  postContentMediaInput: PostContentMediaInput,
): string {
  return JSON.stringify(
    PostContentMediaInput$outboundSchema.parse(postContentMediaInput),
  );
}
