/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Project = {
  /**
   * Project identifier.
   */
  id: string;
  /**
   * Human-readable project name.
   */
  name: string;
};

/** @internal */
export const Project$inboundSchema: z.ZodMiniType<Project, unknown> = z.object({
  id: types.string(),
  name: types.string(),
});

export function projectFromJSON(
  jsonString: string,
): SafeParseResult<Project, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Project$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Project' from JSON`,
  );
}
