/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublishNowPostSchedule = {
  type: "PUBLISH_NOW";
};

/** @internal */
export const PublishNowPostSchedule$inboundSchema: z.ZodMiniType<
  PublishNowPostSchedule,
  unknown
> = z.object({
  type: types.literal("PUBLISH_NOW"),
});
/** @internal */
export type PublishNowPostSchedule$Outbound = {
  type: "PUBLISH_NOW";
};

/** @internal */
export const PublishNowPostSchedule$outboundSchema: z.ZodMiniType<
  PublishNowPostSchedule$Outbound,
  PublishNowPostSchedule
> = z.object({
  type: z.literal("PUBLISH_NOW"),
});

export function publishNowPostScheduleToJSON(
  publishNowPostSchedule: PublishNowPostSchedule,
): string {
  return JSON.stringify(
    PublishNowPostSchedule$outboundSchema.parse(publishNowPostSchedule),
  );
}
export function publishNowPostScheduleFromJSON(
  jsonString: string,
): SafeParseResult<PublishNowPostSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublishNowPostSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublishNowPostSchedule' from JSON`,
  );
}
