/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ScheduleForLaterPostSchedule = {
  type: "SCHEDULE_FOR_LATER";
  /**
   * UTC time when the post should be published.
   */
  scheduledForUTC: Date;
};

/** @internal */
export const ScheduleForLaterPostSchedule$inboundSchema: z.ZodMiniType<
  ScheduleForLaterPostSchedule,
  unknown
> = z.object({
  type: types.literal("SCHEDULE_FOR_LATER"),
  scheduledForUTC: types.date(),
});
/** @internal */
export type ScheduleForLaterPostSchedule$Outbound = {
  type: "SCHEDULE_FOR_LATER";
  scheduledForUTC: string;
};

/** @internal */
export const ScheduleForLaterPostSchedule$outboundSchema: z.ZodMiniType<
  ScheduleForLaterPostSchedule$Outbound,
  ScheduleForLaterPostSchedule
> = z.object({
  type: z.literal("SCHEDULE_FOR_LATER"),
  scheduledForUTC: z.pipe(z.date(), z.transform(v => v.toISOString())),
});

export function scheduleForLaterPostScheduleToJSON(
  scheduleForLaterPostSchedule: ScheduleForLaterPostSchedule,
): string {
  return JSON.stringify(
    ScheduleForLaterPostSchedule$outboundSchema.parse(
      scheduleForLaterPostSchedule,
    ),
  );
}
export function scheduleForLaterPostScheduleFromJSON(
  jsonString: string,
): SafeParseResult<ScheduleForLaterPostSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduleForLaterPostSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduleForLaterPostSchedule' from JSON`,
  );
}
