/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Social platform supported by WoopSocial.
 */
export const SocialPlatform = {
  Pinterest: "PINTEREST",
  Linkedin: "LINKEDIN",
  LinkedinPages: "LINKEDIN_PAGES",
  Instagram: "INSTAGRAM",
  Facebook: "FACEBOOK",
  Tiktok: "TIKTOK",
  X: "X",
  Youtube: "YOUTUBE",
} as const;
/**
 * Social platform supported by WoopSocial.
 */
export type SocialPlatform = OpenEnum<typeof SocialPlatform>;

/** @internal */
export const SocialPlatform$inboundSchema: z.ZodMiniType<
  SocialPlatform,
  unknown
> = openEnums.inboundSchema(SocialPlatform);
/** @internal */
export const SocialPlatform$outboundSchema: z.ZodMiniType<
  string,
  SocialPlatform
> = openEnums.outboundSchema(SocialPlatform);
