/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PinterestSocialAccountPlatformSpecificInputs,
  PinterestSocialAccountPlatformSpecificInputs$inboundSchema,
} from "./pinterest-social-account-platform-specific-inputs.js";
import {
  TikTokSocialAccountPlatformSpecificInputs,
  TikTokSocialAccountPlatformSpecificInputs$inboundSchema,
} from "./tik-tok-social-account-platform-specific-inputs.js";

export type SocialAccountPlatformSpecificInputs =
  | PinterestSocialAccountPlatformSpecificInputs
  | TikTokSocialAccountPlatformSpecificInputs
  | discriminatedUnionTypes.Unknown<"platform">;

/** @internal */
export const SocialAccountPlatformSpecificInputs$inboundSchema: z.ZodMiniType<
  SocialAccountPlatformSpecificInputs,
  unknown
> = discriminatedUnion("platform", {
  PINTEREST: PinterestSocialAccountPlatformSpecificInputs$inboundSchema,
  TIKTOK: TikTokSocialAccountPlatformSpecificInputs$inboundSchema,
});

export function socialAccountPlatformSpecificInputsFromJSON(
  jsonString: string,
): SafeParseResult<SocialAccountPlatformSpecificInputs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SocialAccountPlatformSpecificInputs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialAccountPlatformSpecificInputs' from JSON`,
  );
}
