/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SocialAccountStatus,
  SocialAccountStatus$inboundSchema,
} from "./social-account-status.js";
import {
  SocialPlatform,
  SocialPlatform$inboundSchema,
} from "./social-platform.js";

export type SocialAccount = {
  /**
   * Social account identifier.
   */
  id: string;
  /**
   * Identifies which social media platform this data structure targets.
   *
   * @remarks
   */
  platform: SocialPlatform;
  /**
   * Display name or username for the connected account.
   */
  username: string;
  /**
   * Profile image URL for the connected account.
   */
  imageUrl: string;
  status: SocialAccountStatus;
};

/** @internal */
export const SocialAccount$inboundSchema: z.ZodMiniType<
  SocialAccount,
  unknown
> = z.object({
  id: types.string(),
  platform: SocialPlatform$inboundSchema,
  username: types.string(),
  imageUrl: types.string(),
  status: SocialAccountStatus$inboundSchema,
});

export function socialAccountFromJSON(
  jsonString: string,
): SafeParseResult<SocialAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialAccount' from JSON`,
  );
}
