/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { FacebookPost, FacebookPost$inboundSchema } from "./facebook-post.js";
import {
  InstagramPost,
  InstagramPost$inboundSchema,
} from "./instagram-post.js";
import {
  LinkedInPagesPost,
  LinkedInPagesPost$inboundSchema,
} from "./linked-in-pages-post.js";
import { LinkedInPost, LinkedInPost$inboundSchema } from "./linked-in-post.js";
import {
  PinterestPost,
  PinterestPost$inboundSchema,
} from "./pinterest-post.js";
import { TikTokPost, TikTokPost$inboundSchema } from "./tik-tok-post.js";
import { WoopTestPost, WoopTestPost$inboundSchema } from "./woop-test-post.js";
import { XPost, XPost$inboundSchema } from "./x-post.js";
import { YouTubePost, YouTubePost$inboundSchema } from "./you-tube-post.js";

export type SocialAccountPost =
  | PinterestPost
  | InstagramPost
  | FacebookPost
  | TikTokPost
  | YouTubePost
  | XPost
  | LinkedInPost
  | LinkedInPagesPost
  | WoopTestPost
  | discriminatedUnionTypes.Unknown<"platform">;

/** @internal */
export const SocialAccountPost$inboundSchema: z.ZodMiniType<
  SocialAccountPost,
  unknown
> = discriminatedUnion("platform", {
  PINTEREST: PinterestPost$inboundSchema,
  INSTAGRAM: InstagramPost$inboundSchema,
  FACEBOOK: FacebookPost$inboundSchema,
  TIKTOK: TikTokPost$inboundSchema,
  YOUTUBE: YouTubePost$inboundSchema,
  X: XPost$inboundSchema,
  LINKEDIN: LinkedInPost$inboundSchema,
  LINKEDIN_PAGES: LinkedInPagesPost$inboundSchema,
  WOOPTEST: WoopTestPost$inboundSchema,
});

export function socialAccountPostFromJSON(
  jsonString: string,
): SafeParseResult<SocialAccountPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialAccountPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialAccountPost' from JSON`,
  );
}
