/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  FacebookInput,
  FacebookInput$Outbound,
  FacebookInput$outboundSchema,
} from "./facebook-input.js";
import {
  InstagramInput,
  InstagramInput$Outbound,
  InstagramInput$outboundSchema,
} from "./instagram-input.js";
import {
  LinkedInInput,
  LinkedInInput$Outbound,
  LinkedInInput$outboundSchema,
} from "./linked-in-input.js";
import {
  LinkedInPagesInput,
  LinkedInPagesInput$Outbound,
  LinkedInPagesInput$outboundSchema,
} from "./linked-in-pages-input.js";
import {
  PinterestInput,
  PinterestInput$Outbound,
  PinterestInput$outboundSchema,
} from "./pinterest-input.js";
import {
  TikTokInput,
  TikTokInput$Outbound,
  TikTokInput$outboundSchema,
} from "./tik-tok-input.js";
import { XInput, XInput$Outbound, XInput$outboundSchema } from "./x-input.js";
import {
  YouTubeInput,
  YouTubeInput$Outbound,
  YouTubeInput$outboundSchema,
} from "./you-tube-input.js";

export type SocialAccountTargetInput =
  | PinterestInput
  | InstagramInput
  | FacebookInput
  | TikTokInput
  | YouTubeInput
  | XInput
  | LinkedInInput
  | LinkedInPagesInput;

/** @internal */
export type SocialAccountTargetInput$Outbound =
  | PinterestInput$Outbound
  | InstagramInput$Outbound
  | FacebookInput$Outbound
  | TikTokInput$Outbound
  | YouTubeInput$Outbound
  | XInput$Outbound
  | LinkedInInput$Outbound
  | LinkedInPagesInput$Outbound;

/** @internal */
export const SocialAccountTargetInput$outboundSchema: z.ZodMiniType<
  SocialAccountTargetInput$Outbound,
  SocialAccountTargetInput
> = z.union([
  PinterestInput$outboundSchema,
  InstagramInput$outboundSchema,
  FacebookInput$outboundSchema,
  TikTokInput$outboundSchema,
  YouTubeInput$outboundSchema,
  XInput$outboundSchema,
  LinkedInInput$outboundSchema,
  LinkedInPagesInput$outboundSchema,
]);

export function socialAccountTargetInputToJSON(
  socialAccountTargetInput: SocialAccountTargetInput,
): string {
  return JSON.stringify(
    SocialAccountTargetInput$outboundSchema.parse(socialAccountTargetInput),
  );
}
