/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const SocialAccountStatus = {
  Connected: "CONNECTED",
  Disconnected: "DISCONNECTED",
} as const;
export type SocialAccountStatus = OpenEnum<typeof SocialAccountStatus>;

/** @internal */
export const SocialAccountStatus$inboundSchema: z.ZodMiniType<
  SocialAccountStatus,
  unknown
> = openEnums.inboundSchema(SocialAccountStatus);
