/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SocialAccountPlatformSpecificInputs,
  SocialAccountPlatformSpecificInputs$inboundSchema,
} from "./social-account-platform-specific-inputs.js";

export type SocialAccountPlatformInputs = {
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  platformSpecificInputs: SocialAccountPlatformSpecificInputs;
};

/** @internal */
export const SocialAccountPlatformInputs$inboundSchema: z.ZodMiniType<
  SocialAccountPlatformInputs,
  unknown
> = z.object({
  socialAccountId: types.string(),
  platformSpecificInputs: SocialAccountPlatformSpecificInputs$inboundSchema,
});

export function socialAccountPlatformInputsFromJSON(
  jsonString: string,
): SafeParseResult<SocialAccountPlatformInputs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialAccountPlatformInputs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialAccountPlatformInputs' from JSON`,
  );
}
