/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TikTokAccountPlatformInputs,
  TikTokAccountPlatformInputs$inboundSchema,
} from "./tik-tok-account-platform-inputs.js";

export type TikTokSocialAccountPlatformSpecificInputs = {
  platform: "TIKTOK";
  tiktok: TikTokAccountPlatformInputs;
};

/** @internal */
export const TikTokSocialAccountPlatformSpecificInputs$inboundSchema:
  z.ZodMiniType<TikTokSocialAccountPlatformSpecificInputs, unknown> = z.object({
    platform: types.literal("TIKTOK"),
    tiktok: TikTokAccountPlatformInputs$inboundSchema,
  });

export function tikTokSocialAccountPlatformSpecificInputsFromJSON(
  jsonString: string,
): SafeParseResult<
  TikTokSocialAccountPlatformSpecificInputs,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TikTokSocialAccountPlatformSpecificInputs$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TikTokSocialAccountPlatformSpecificInputs' from JSON`,
  );
}
