/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TikTokPostType = {
  Video: "VIDEO",
  Photo: "PHOTO",
} as const;
export type TikTokPostType = OpenEnum<typeof TikTokPostType>;

/** @internal */
export const TikTokPostType$inboundSchema: z.ZodMiniType<
  TikTokPostType,
  unknown
> = openEnums.inboundSchema(TikTokPostType);
/** @internal */
export const TikTokPostType$outboundSchema: z.ZodMiniType<
  string,
  TikTokPostType
> = openEnums.outboundSchema(TikTokPostType);
