/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";
import {
  TikTokPostType,
  TikTokPostType$outboundSchema,
} from "./tik-tok-post-type.js";
import {
  TikTokPrivacyLevel,
  TikTokPrivacyLevel$outboundSchema,
} from "./tik-tok-privacy-level.js";

export type TikTokInput = {
  platform: "TIKTOK";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
  postType: TikTokPostType;
  privacyLevel: TikTokPrivacyLevel;
  /**
   * Whether comments should be allowed for this TikTok post.
   */
  allowComment: boolean;
  /**
   * Whether duets should be allowed for this TikTok post.
   *
   * @remarks
   *
   * This field applies to `postType=VIDEO`.
   *
   * When `postType=PHOTO`, this field is required by the API contract
   * but is not used by TikTok.
   */
  allowDuet: boolean;
  /**
   * Whether stitches should be allowed for this TikTok post.
   *
   * @remarks
   *
   * This field applies to `postType=VIDEO`.
   *
   * When `postType=PHOTO`, this field is required by the API contract
   * but is not used by TikTok.
   */
  allowStitch: boolean;
  /**
   * Whether the post should be disclosed as "Your brand" content on TikTok.
   */
  isYourBrand: boolean;
  /**
   * Whether the post should be disclosed as branded content on TikTok.
   */
  isBrandedContent: boolean;
  /**
   * Whether TikTok should automatically add music to this post.
   *
   * @remarks
   *
   * This field applies to `postType=PHOTO`.
   *
   * When `postType=VIDEO`, this field is required by the API contract
   * but is not used by TikTok.
   */
  autoAddMusic: boolean;
};

/** @internal */
export type TikTokInput$Outbound = {
  platform: "TIKTOK";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
  postType: string;
  privacyLevel: string;
  allowComment: boolean;
  allowDuet: boolean;
  allowStitch: boolean;
  isYourBrand: boolean;
  isBrandedContent: boolean;
  autoAddMusic: boolean;
};

/** @internal */
export const TikTokInput$outboundSchema: z.ZodMiniType<
  TikTokInput$Outbound,
  TikTokInput
> = z.object({
  platform: z.literal("TIKTOK"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
  postType: TikTokPostType$outboundSchema,
  privacyLevel: TikTokPrivacyLevel$outboundSchema,
  allowComment: z.boolean(),
  allowDuet: z.boolean(),
  allowStitch: z.boolean(),
  isYourBrand: z.boolean(),
  isBrandedContent: z.boolean(),
  autoAddMusic: z.boolean(),
});

export function tikTokInputToJSON(tikTokInput: TikTokInput): string {
  return JSON.stringify(TikTokInput$outboundSchema.parse(tikTokInput));
}
