/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TikTokPrivacyLevel,
  TikTokPrivacyLevel$inboundSchema,
} from "./tik-tok-privacy-level.js";

export type TikTokAccountPlatformInputs = {
  /**
   * Privacy values currently allowed for this TikTok account.
   *
   * @remarks
   *
   * Each value can be sent as `platformSpecifics.privacyLevel`
   * when creating a post.
   */
  privacyLevelOptions: Array<TikTokPrivacyLevel>;
  /**
   * Whether TikTok currently disables comments for this account.
   */
  commentDisabled: boolean;
  /**
   * Whether TikTok currently disables duets for this account.
   */
  duetDisabled: boolean;
  /**
   * Whether TikTok currently disables stitches for this account.
   */
  stitchDisabled: boolean;
  /**
   * Maximum TikTok video duration currently allowed for this account.
   */
  maxVideoPostDurationSec: number;
};

/** @internal */
export const TikTokAccountPlatformInputs$inboundSchema: z.ZodMiniType<
  TikTokAccountPlatformInputs,
  unknown
> = z.object({
  privacyLevelOptions: z.array(TikTokPrivacyLevel$inboundSchema),
  commentDisabled: types.boolean(),
  duetDisabled: types.boolean(),
  stitchDisabled: types.boolean(),
  maxVideoPostDurationSec: types.number(),
});

export function tikTokAccountPlatformInputsFromJSON(
  jsonString: string,
): SafeParseResult<TikTokAccountPlatformInputs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TikTokAccountPlatformInputs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TikTokAccountPlatformInputs' from JSON`,
  );
}
