/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TikTokPrivacyLevel = {
  PublicToEveryone: "PUBLIC_TO_EVERYONE",
  SelfOnly: "SELF_ONLY",
  MutualFollowFriends: "MUTUAL_FOLLOW_FRIENDS",
  FollowerOfCreator: "FOLLOWER_OF_CREATOR",
} as const;
export type TikTokPrivacyLevel = OpenEnum<typeof TikTokPrivacyLevel>;

/** @internal */
export const TikTokPrivacyLevel$inboundSchema: z.ZodMiniType<
  TikTokPrivacyLevel,
  unknown
> = openEnums.inboundSchema(TikTokPrivacyLevel);
/** @internal */
export const TikTokPrivacyLevel$outboundSchema: z.ZodMiniType<
  string,
  TikTokPrivacyLevel
> = openEnums.outboundSchema(TikTokPrivacyLevel);
