/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TikTokPostType,
  TikTokPostType$inboundSchema,
  TikTokPostType$outboundSchema,
} from "./tik-tok-post-type.js";
import {
  TikTokPrivacyLevel,
  TikTokPrivacyLevel$inboundSchema,
  TikTokPrivacyLevel$outboundSchema,
} from "./tik-tok-privacy-level.js";

export type TikTokSpecifics = {
  platform: "TIKTOK";
  postType: TikTokPostType;
  privacyLevel: TikTokPrivacyLevel;
  allowComment: boolean;
  allowDuet: boolean;
  allowStitch: boolean;
  contentDisclosureEnabled: boolean;
  isYourBrand: boolean;
  isBrandedContent: boolean;
  autoAddMusic: boolean;
};

/** @internal */
export const TikTokSpecifics$inboundSchema: z.ZodMiniType<
  TikTokSpecifics,
  unknown
> = z.object({
  platform: types.literal("TIKTOK"),
  postType: TikTokPostType$inboundSchema,
  privacyLevel: TikTokPrivacyLevel$inboundSchema,
  allowComment: types.boolean(),
  allowDuet: types.boolean(),
  allowStitch: types.boolean(),
  contentDisclosureEnabled: types.boolean(),
  isYourBrand: types.boolean(),
  isBrandedContent: types.boolean(),
  autoAddMusic: types.boolean(),
});
/** @internal */
export type TikTokSpecifics$Outbound = {
  platform: "TIKTOK";
  postType: string;
  privacyLevel: string;
  allowComment: boolean;
  allowDuet: boolean;
  allowStitch: boolean;
  contentDisclosureEnabled: boolean;
  isYourBrand: boolean;
  isBrandedContent: boolean;
  autoAddMusic: boolean;
};

/** @internal */
export const TikTokSpecifics$outboundSchema: z.ZodMiniType<
  TikTokSpecifics$Outbound,
  TikTokSpecifics
> = z.object({
  platform: z.literal("TIKTOK"),
  postType: TikTokPostType$outboundSchema,
  privacyLevel: TikTokPrivacyLevel$outboundSchema,
  allowComment: z.boolean(),
  allowDuet: z.boolean(),
  allowStitch: z.boolean(),
  contentDisclosureEnabled: z.boolean(),
  isYourBrand: z.boolean(),
  isBrandedContent: z.boolean(),
  autoAddMusic: z.boolean(),
});

export function tikTokSpecificsToJSON(
  tikTokSpecifics: TikTokSpecifics,
): string {
  return JSON.stringify(TikTokSpecifics$outboundSchema.parse(tikTokSpecifics));
}
export function tikTokSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<TikTokSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TikTokSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TikTokSpecifics' from JSON`,
  );
}
