/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryStatus,
  DeliveryStatus$inboundSchema,
} from "./delivery-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostContentItem,
  PostContentItem$inboundSchema,
} from "./post-content-item.js";
import {
  TikTokPostType,
  TikTokPostType$inboundSchema,
} from "./tik-tok-post-type.js";
import {
  TikTokPrivacyLevel,
  TikTokPrivacyLevel$inboundSchema,
} from "./tik-tok-privacy-level.js";

export type TikTokPost = {
  platform: "TIKTOK";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Delivery lifecycle status for a post.
   *
   * @remarks
   *
   * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
   * `SENDING`: Delivery is currently in progress.
   * `SENT`: Delivery completed successfully.
   * `FAILED`: Delivery completed unsuccessfully.
   */
  deliveryStatus: DeliveryStatus;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is returned.
   */
  contentOverride?: Array<PostContentItem> | undefined;
  sentAt?: Date | undefined;
  externalPostId?: string | undefined;
  externalPostUrl?: string | undefined;
  errorMessage?: string | undefined;
  postType: TikTokPostType;
  privacyLevel: TikTokPrivacyLevel;
  /**
   * Whether comments should be allowed for this TikTok post.
   */
  allowComment: boolean;
  /**
   * Whether duets should be allowed for this TikTok post.
   *
   * @remarks
   *
   * This field applies to `postType=VIDEO`.
   *
   * When `postType=PHOTO`, this field is required by the API contract
   * but is not used by TikTok.
   */
  allowDuet: boolean;
  /**
   * Whether stitches should be allowed for this TikTok post.
   *
   * @remarks
   *
   * This field applies to `postType=VIDEO`.
   *
   * When `postType=PHOTO`, this field is required by the API contract
   * but is not used by TikTok.
   */
  allowStitch: boolean;
  /**
   * Whether TikTok content disclosure should be enabled for this post.
   */
  contentDisclosureEnabled: boolean;
  /**
   * Whether the post should be disclosed as "Your brand" content on TikTok.
   */
  isYourBrand: boolean;
  /**
   * Whether the post should be disclosed as branded content on TikTok.
   */
  isBrandedContent: boolean;
  /**
   * Whether TikTok should automatically add music to this post.
   *
   * @remarks
   *
   * This field applies to `postType=PHOTO`.
   *
   * When `postType=VIDEO`, this field is required by the API contract
   * but is not used by TikTok.
   */
  autoAddMusic: boolean;
};

/** @internal */
export const TikTokPost$inboundSchema: z.ZodMiniType<TikTokPost, unknown> = z
  .object({
    platform: types.literal("TIKTOK"),
    socialAccountId: types.string(),
    deliveryStatus: DeliveryStatus$inboundSchema,
    contentOverride: types.optional(z.array(PostContentItem$inboundSchema)),
    sentAt: types.optional(types.date()),
    externalPostId: types.optional(types.string()),
    externalPostUrl: types.optional(types.string()),
    errorMessage: types.optional(types.string()),
    postType: TikTokPostType$inboundSchema,
    privacyLevel: TikTokPrivacyLevel$inboundSchema,
    allowComment: types.boolean(),
    allowDuet: types.boolean(),
    allowStitch: types.boolean(),
    contentDisclosureEnabled: types.boolean(),
    isYourBrand: types.boolean(),
    isBrandedContent: types.boolean(),
    autoAddMusic: types.boolean(),
  });

export function tikTokPostFromJSON(
  jsonString: string,
): SafeParseResult<TikTokPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TikTokPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TikTokPost' from JSON`,
  );
}
