/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  UpdatePostResult,
  UpdatePostResult$inboundSchema,
} from "./update-post-result.js";

export type UpdatePostsResponse = {
  /**
   * Results in the same order as the request items.
   */
  results: Array<UpdatePostResult>;
};

/** @internal */
export const UpdatePostsResponse$inboundSchema: z.ZodMiniType<
  UpdatePostsResponse,
  unknown
> = z.object({
  results: z.array(UpdatePostResult$inboundSchema),
});

export function updatePostsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePostsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePostsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePostsResponse' from JSON`,
  );
}
