/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const UpdatePostFailureCode = {
  PostNotFound: "POST_NOT_FOUND",
  PostNotUpdatable: "POST_NOT_UPDATABLE",
  InvalidMediaId: "INVALID_MEDIA_ID",
  InvalidPlatformSpecificData: "INVALID_PLATFORM_SPECIFIC_DATA",
  ValidationFailed: "VALIDATION_FAILED",
  InternalError: "INTERNAL_ERROR",
} as const;
export type UpdatePostFailureCode = OpenEnum<typeof UpdatePostFailureCode>;

/** @internal */
export const UpdatePostFailureCode$inboundSchema: z.ZodMiniType<
  UpdatePostFailureCode,
  unknown
> = openEnums.inboundSchema(UpdatePostFailureCode);
