/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PlatformSpecifics,
  PlatformSpecifics$Outbound,
  PlatformSpecifics$outboundSchema,
} from "./platform-specifics.js";

export type UpdatePostItem = {
  /**
   * Post to update.
   */
  id: string;
  /**
   * UTC time when this post should be published.
   */
  scheduledForUTC: Date;
  title?: string | undefined;
  description?: string | undefined;
  firstComment?: string | undefined;
  /**
   * Media identifiers previously created via the media upload flow.
   */
  mediaIds?: Array<string> | undefined;
  /**
   * Platform-specific publishing options. The `platform` value must match the publishing account's platform.
   */
  platformSpecifics: PlatformSpecifics;
};

/** @internal */
export type UpdatePostItem$Outbound = {
  id: string;
  scheduledForUTC: string;
  title?: string | undefined;
  description?: string | undefined;
  firstComment?: string | undefined;
  mediaIds?: Array<string> | undefined;
  platformSpecifics: PlatformSpecifics$Outbound;
};

/** @internal */
export const UpdatePostItem$outboundSchema: z.ZodMiniType<
  UpdatePostItem$Outbound,
  UpdatePostItem
> = z.object({
  id: z.string(),
  scheduledForUTC: z.pipe(z.date(), z.transform(v => v.toISOString())),
  title: z.optional(z.string()),
  description: z.optional(z.string()),
  firstComment: z.optional(z.string()),
  mediaIds: z.optional(z.array(z.string())),
  platformSpecifics: PlatformSpecifics$outboundSchema,
});

export function updatePostItemToJSON(updatePostItem: UpdatePostItem): string {
  return JSON.stringify(UpdatePostItem$outboundSchema.parse(updatePostItem));
}
