/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const UploadSessionStatusValue = {
  Initiated: "INITIATED",
  Uploaded: "UPLOADED",
  Ready: "READY",
  Failed: "FAILED",
  Aborted: "ABORTED",
} as const;
export type UploadSessionStatusValue = OpenEnum<
  typeof UploadSessionStatusValue
>;

/** @internal */
export const UploadSessionStatusValue$inboundSchema: z.ZodMiniType<
  UploadSessionStatusValue,
  unknown
> = openEnums.inboundSchema(UploadSessionStatusValue);
