/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  UploadSessionStatusValue,
  UploadSessionStatusValue$inboundSchema,
} from "./upload-session-status-value.js";

export type UploadSessionStatus = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
  status: UploadSessionStatusValue;
  mediaId?: string | undefined;
  failureCode?: string | undefined;
  failureMessage?: string | undefined;
};

/** @internal */
export const UploadSessionStatus$inboundSchema: z.ZodMiniType<
  UploadSessionStatus,
  unknown
> = z.object({
  uploadSessionId: types.string(),
  status: UploadSessionStatusValue$inboundSchema,
  mediaId: types.optional(types.string()),
  failureCode: types.optional(types.string()),
  failureMessage: types.optional(types.string()),
});

export function uploadSessionStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionStatus' from JSON`,
  );
}
