/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  UploadSessionPart,
  UploadSessionPart$inboundSchema,
} from "./upload-session-part.js";

export type UploadSession = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
  /**
   * Maximum chunk size to use when slicing the file into parts.
   *
   * @remarks
   *
   * For uploads with more than one part, every part except the last must
   * be exactly this size. The last part may be smaller. For a single-part
   * upload, the only part may be smaller than this size.
   */
  partSizeInBytes: number;
  /**
   * Number of parts that must be uploaded before completion.
   */
  partCount: number;
  /**
   * Time when the presigned part upload URLs expire.
   */
  expiresAt: Date;
  /**
   * Presigned upload targets, in part-number order.
   */
  parts: Array<UploadSessionPart>;
};

/** @internal */
export const UploadSession$inboundSchema: z.ZodMiniType<
  UploadSession,
  unknown
> = z.object({
  uploadSessionId: types.string(),
  partSizeInBytes: types.number(),
  partCount: types.number(),
  expiresAt: types.date(),
  parts: z.array(UploadSessionPart$inboundSchema),
});

export function uploadSessionFromJSON(
  jsonString: string,
): SafeParseResult<UploadSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSession' from JSON`,
  );
}
