/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UploadSessionUploadedStatus = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
  status: "UPLOADED";
};

/** @internal */
export const UploadSessionUploadedStatus$inboundSchema: z.ZodMiniType<
  UploadSessionUploadedStatus,
  unknown
> = z.object({
  uploadSessionId: types.string(),
  status: types.literal("UPLOADED"),
});

export function uploadSessionUploadedStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionUploadedStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionUploadedStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionUploadedStatus' from JSON`,
  );
}
