/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UploadSessionFailedStatus = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
  status: "FAILED";
  /**
   * Machine-readable failure code for the upload session.
   */
  failureCode: string;
  /**
   * Human-readable summary of why the upload session failed.
   */
  failureMessage: string;
};

/** @internal */
export const UploadSessionFailedStatus$inboundSchema: z.ZodMiniType<
  UploadSessionFailedStatus,
  unknown
> = z.object({
  uploadSessionId: types.string(),
  status: types.literal("FAILED"),
  failureCode: types.string(),
  failureMessage: types.string(),
});

export function uploadSessionFailedStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionFailedStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionFailedStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionFailedStatus' from JSON`,
  );
}
