/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  UploadSessionAbortedStatus,
  UploadSessionAbortedStatus$inboundSchema,
} from "./upload-session-aborted-status.js";
import {
  UploadSessionFailedStatus,
  UploadSessionFailedStatus$inboundSchema,
} from "./upload-session-failed-status.js";
import {
  UploadSessionInitiatedStatus,
  UploadSessionInitiatedStatus$inboundSchema,
} from "./upload-session-initiated-status.js";
import {
  UploadSessionReadyStatus,
  UploadSessionReadyStatus$inboundSchema,
} from "./upload-session-ready-status.js";
import {
  UploadSessionUploadedStatus,
  UploadSessionUploadedStatus$inboundSchema,
} from "./upload-session-uploaded-status.js";

export type UploadSessionStatus =
  | UploadSessionInitiatedStatus
  | UploadSessionUploadedStatus
  | UploadSessionReadyStatus
  | UploadSessionFailedStatus
  | UploadSessionAbortedStatus
  | discriminatedUnionTypes.Unknown<"status">;

/** @internal */
export const UploadSessionStatus$inboundSchema: z.ZodMiniType<
  UploadSessionStatus,
  unknown
> = discriminatedUnion("status", {
  INITIATED: UploadSessionInitiatedStatus$inboundSchema,
  UPLOADED: UploadSessionUploadedStatus$inboundSchema,
  READY: UploadSessionReadyStatus$inboundSchema,
  FAILED: UploadSessionFailedStatus$inboundSchema,
  ABORTED: UploadSessionAbortedStatus$inboundSchema,
});

export function uploadSessionStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionStatus' from JSON`,
  );
}
