/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UploadSessionReadyStatus = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
  status: "READY";
  /**
   * Media identifier created by the completed upload.
   */
  mediaId: string;
};

/** @internal */
export const UploadSessionReadyStatus$inboundSchema: z.ZodMiniType<
  UploadSessionReadyStatus,
  unknown
> = z.object({
  uploadSessionId: types.string(),
  status: types.literal("READY"),
  mediaId: types.string(),
});

export function uploadSessionReadyStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionReadyStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionReadyStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionReadyStatus' from JSON`,
  );
}
