/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UploadSessionInitiatedStatus = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
  status: "INITIATED";
};

/** @internal */
export const UploadSessionInitiatedStatus$inboundSchema: z.ZodMiniType<
  UploadSessionInitiatedStatus,
  unknown
> = z.object({
  uploadSessionId: types.string(),
  status: types.literal("INITIATED"),
});

export function uploadSessionInitiatedStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionInitiatedStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionInitiatedStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionInitiatedStatus' from JSON`,
  );
}
