/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UploadSessionPart = {
  /**
   * 1-based part number to upload to this URL.
   */
  partNumber: number;
  /**
   * Presigned URL that accepts the bytes for `partNumber`.
   */
  uploadUrl: string;
};

/** @internal */
export const UploadSessionPart$inboundSchema: z.ZodMiniType<
  UploadSessionPart,
  unknown
> = z.object({
  partNumber: types.number(),
  uploadUrl: types.string(),
});

export function uploadSessionPartFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionPart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionPart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionPart' from JSON`,
  );
}
