/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UploadSessionAbortedStatus = {
  /**
   * Media upload session identifier.
   */
  uploadSessionId: string;
  status: "ABORTED";
};

/** @internal */
export const UploadSessionAbortedStatus$inboundSchema: z.ZodMiniType<
  UploadSessionAbortedStatus,
  unknown
> = z.object({
  uploadSessionId: types.string(),
  status: types.literal("ABORTED"),
});

export function uploadSessionAbortedStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionAbortedStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionAbortedStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionAbortedStatus' from JSON`,
  );
}
