/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
} from "./validation-error.js";
import {
  ValidationWarning,
  ValidationWarning$inboundSchema,
} from "./validation-warning.js";

export type ValidatePostResponse = {
  /**
   * Whether the request passed validation.
   */
  isValid: boolean;
  /**
   * Blocking validation errors. Empty when the request is valid.
   */
  errors: Array<ValidationError>;
  /**
   * Non-blocking validation warnings. Empty when there are no warnings.
   */
  warnings: Array<ValidationWarning>;
};

/** @internal */
export const ValidatePostResponse$inboundSchema: z.ZodMiniType<
  ValidatePostResponse,
  unknown
> = z.object({
  isValid: types.boolean(),
  errors: z.array(ValidationError$inboundSchema),
  warnings: z.array(ValidationWarning$inboundSchema),
});

export function validatePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<ValidatePostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidatePostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidatePostResponse' from JSON`,
  );
}
