/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ValidationField = {
  Description: "DESCRIPTION",
  Media: "MEDIA",
  PinterestBoard: "PINTEREST_BOARD",
  Content: "CONTENT",
  Title: "TITLE",
  FirstComment: "FIRST_COMMENT",
  TiktokPrivacyLevel: "TIKTOK_PRIVACY_LEVEL",
  TiktokContentDisclosure: "TIKTOK_CONTENT_DISCLOSURE",
  YoutubePrivacy: "YOUTUBE_PRIVACY",
  YoutubeCategory: "YOUTUBE_CATEGORY",
  YoutubeTags: "YOUTUBE_TAGS",
  Schedule: "SCHEDULE",
} as const;
export type ValidationField = OpenEnum<typeof ValidationField>;

/** @internal */
export const ValidationField$inboundSchema: z.ZodMiniType<
  ValidationField,
  unknown
> = openEnums.inboundSchema(ValidationField);
