/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ValidationField,
  ValidationField$inboundSchema,
} from "./validation-field.js";

export type ValidationWarning = {
  field: ValidationField;
  message: string;
};

/** @internal */
export const ValidationWarning$inboundSchema: z.ZodMiniType<
  ValidationWarning,
  unknown
> = z.object({
  field: ValidationField$inboundSchema,
  message: types.string(),
});

export function validationWarningFromJSON(
  jsonString: string,
): SafeParseResult<ValidationWarning, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidationWarning$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidationWarning' from JSON`,
  );
}
