/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ValidationField,
  ValidationField$inboundSchema,
} from "./validation-field.js";

export type ValidationError = {
  field: ValidationField;
  message: string;
};

/** @internal */
export const ValidationError$inboundSchema: z.ZodMiniType<
  ValidationError,
  unknown
> = z.object({
  field: ValidationField$inboundSchema,
  message: types.string(),
});

export function validationErrorFromJSON(
  jsonString: string,
): SafeParseResult<ValidationError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidationError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidationError' from JSON`,
  );
}
