/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
} from "./webhook-event-type.js";

export type WebhookEndpoint = {
  /**
   * Webhook endpoint identifier (int64 as string).
   */
  id: string;
  url: string;
  eventTypes: Array<WebhookEventType>;
  createdAt: Date;
  /**
   * Base64-encoded 32-byte signing secret. Returned once on creation only.
   */
  signingSecret?: string | undefined;
};

/** @internal */
export const WebhookEndpoint$inboundSchema: z.ZodMiniType<
  WebhookEndpoint,
  unknown
> = z.object({
  id: types.string(),
  url: types.string(),
  eventTypes: z.array(WebhookEventType$inboundSchema),
  createdAt: types.date(),
  signingSecret: types.optional(types.string()),
});

export function webhookEndpointFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEndpoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEndpoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEndpoint' from JSON`,
  );
}
