/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryStatus,
  DeliveryStatus$inboundSchema,
} from "./delivery-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostContentItem,
  PostContentItem$inboundSchema,
} from "./post-content-item.js";
import { PostSchedule, PostSchedule$inboundSchema } from "./post-schedule.js";

export type WoopTestPost = {
  platform: "WOOPTEST";
  /**
   * Social account post identifier.
   */
  socialAccountPostId: string;
  /**
   * Parent post identifier.
   */
  postId: string;
  /**
   * Project identifier.
   */
  projectId: string;
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Delivery lifecycle status for a post.
   *
   * @remarks
   *
   * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
   * `SENDING`: Delivery is currently in progress.
   * `SENT`: Delivery completed successfully.
   * `FAILED`: Delivery completed unsuccessfully.
   */
  deliveryStatus: DeliveryStatus;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is returned.
   */
  content: Array<PostContentItem>;
  schedule: PostSchedule;
  /**
   * UTC time when the social account post was created.
   */
  createdAt: Date;
  /**
   * UTC time when the social account post was last updated.
   */
  updatedAt: Date;
  /**
   * UTC time when the latest delivery attempt for this social account post completed both for successful (`SENT`) and unsuccessful (`FAILED`) terminal `deliveryStatus` values.
   */
  deliveryCompletedAt?: Date | undefined;
  externalPostId?: string | undefined;
  externalPostUrl?: string | undefined;
  errorMessage?: string | undefined;
  /**
   * Whether the simulated delivery should succeed or fail.
   *
   * @remarks
   *
   * Defaults to `true`. Set to `false` to simulate a delivery failure.
   */
  shouldSucceed: boolean;
};

/** @internal */
export const WoopTestPost$inboundSchema: z.ZodMiniType<WoopTestPost, unknown> =
  z.object({
    platform: types.literal("WOOPTEST"),
    socialAccountPostId: types.string(),
    postId: types.string(),
    projectId: types.string(),
    socialAccountId: types.string(),
    deliveryStatus: DeliveryStatus$inboundSchema,
    content: z.array(PostContentItem$inboundSchema),
    schedule: PostSchedule$inboundSchema,
    createdAt: types.date(),
    updatedAt: types.date(),
    deliveryCompletedAt: types.optional(types.date()),
    externalPostId: types.optional(types.string()),
    externalPostUrl: types.optional(types.string()),
    errorMessage: types.optional(types.string()),
    shouldSucceed: z._default(types.boolean(), true),
  });

export function woopTestPostFromJSON(
  jsonString: string,
): SafeParseResult<WoopTestPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WoopTestPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WoopTestPost' from JSON`,
  );
}
