/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";

export type WoopTestInput = {
  platform: "WOOPTEST";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
  /**
   * Whether the simulated delivery should succeed or fail.
   *
   * @remarks
   *
   * Defaults to `true`. Set to `false` to simulate a delivery failure.
   */
  shouldSucceed?: boolean | undefined;
};

/** @internal */
export type WoopTestInput$Outbound = {
  platform: "WOOPTEST";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
  shouldSucceed: boolean;
};

/** @internal */
export const WoopTestInput$outboundSchema: z.ZodMiniType<
  WoopTestInput$Outbound,
  WoopTestInput
> = z.object({
  platform: z.literal("WOOPTEST"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
  shouldSucceed: z._default(z.boolean(), true),
});

export function woopTestInputToJSON(woopTestInput: WoopTestInput): string {
  return JSON.stringify(WoopTestInput$outboundSchema.parse(woopTestInput));
}
