/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";

export type XInput = {
  platform: "X";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
};

/** @internal */
export type XInput$Outbound = {
  platform: "X";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
};

/** @internal */
export const XInput$outboundSchema: z.ZodMiniType<XInput$Outbound, XInput> = z
  .object({
    platform: z.literal("X"),
    socialAccountId: z.string(),
    contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
  });

export function xInputToJSON(xInput: XInput): string {
  return JSON.stringify(XInput$outboundSchema.parse(xInput));
}
