/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type XSpecifics = {
  platform: "X";
};

/** @internal */
export const XSpecifics$inboundSchema: z.ZodMiniType<XSpecifics, unknown> = z
  .object({
    platform: types.literal("X"),
  });
/** @internal */
export type XSpecifics$Outbound = {
  platform: "X";
};

/** @internal */
export const XSpecifics$outboundSchema: z.ZodMiniType<
  XSpecifics$Outbound,
  XSpecifics
> = z.object({
  platform: z.literal("X"),
});

export function xSpecificsToJSON(xSpecifics: XSpecifics): string {
  return JSON.stringify(XSpecifics$outboundSchema.parse(xSpecifics));
}
export function xSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<XSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => XSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'XSpecifics' from JSON`,
  );
}
