/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PostContentItemInput,
  PostContentItemInput$Outbound,
  PostContentItemInput$outboundSchema,
} from "./post-content-item-input.js";
import {
  YouTubePrivacy,
  YouTubePrivacy$outboundSchema,
} from "./you-tube-privacy.js";

export type YouTubeInput = {
  platform: "YOUTUBE";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is supported.
   */
  contentOverride?: Array<PostContentItemInput> | undefined;
  privacy?: YouTubePrivacy | undefined;
  category?: string | undefined;
  tags?: Array<string> | undefined;
  madeForKids?: boolean | undefined;
};

/** @internal */
export type YouTubeInput$Outbound = {
  platform: "YOUTUBE";
  socialAccountId: string;
  contentOverride?: Array<PostContentItemInput$Outbound> | undefined;
  privacy?: string | undefined;
  category?: string | undefined;
  tags?: Array<string> | undefined;
  madeForKids?: boolean | undefined;
};

/** @internal */
export const YouTubeInput$outboundSchema: z.ZodMiniType<
  YouTubeInput$Outbound,
  YouTubeInput
> = z.object({
  platform: z.literal("YOUTUBE"),
  socialAccountId: z.string(),
  contentOverride: z.optional(z.array(PostContentItemInput$outboundSchema)),
  privacy: z.optional(YouTubePrivacy$outboundSchema),
  category: z.optional(z.string()),
  tags: z.optional(z.array(z.string())),
  madeForKids: z.optional(z.boolean()),
});

export function youTubeInputToJSON(youTubeInput: YouTubeInput): string {
  return JSON.stringify(YouTubeInput$outboundSchema.parse(youTubeInput));
}
