/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const YouTubePrivacy = {
  Public: "public",
  Private: "private",
  Unlisted: "unlisted",
} as const;
export type YouTubePrivacy = OpenEnum<typeof YouTubePrivacy>;

/** @internal */
export const YouTubePrivacy$inboundSchema: z.ZodMiniType<
  YouTubePrivacy,
  unknown
> = openEnums.inboundSchema(YouTubePrivacy);
/** @internal */
export const YouTubePrivacy$outboundSchema: z.ZodMiniType<
  string,
  YouTubePrivacy
> = openEnums.outboundSchema(YouTubePrivacy);
