/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  YouTubePrivacy,
  YouTubePrivacy$inboundSchema,
  YouTubePrivacy$outboundSchema,
} from "./you-tube-privacy.js";

export type YouTubeSpecifics = {
  platform: "YOUTUBE";
  privacy?: YouTubePrivacy | undefined;
  category?: string | undefined;
  tags?: Array<string> | undefined;
  madeForKids?: boolean | undefined;
};

/** @internal */
export const YouTubeSpecifics$inboundSchema: z.ZodMiniType<
  YouTubeSpecifics,
  unknown
> = z.object({
  platform: types.literal("YOUTUBE"),
  privacy: types.optional(YouTubePrivacy$inboundSchema),
  category: types.optional(types.string()),
  tags: types.optional(z.array(types.string())),
  madeForKids: types.optional(types.boolean()),
});
/** @internal */
export type YouTubeSpecifics$Outbound = {
  platform: "YOUTUBE";
  privacy?: string | undefined;
  category?: string | undefined;
  tags?: Array<string> | undefined;
  madeForKids?: boolean | undefined;
};

/** @internal */
export const YouTubeSpecifics$outboundSchema: z.ZodMiniType<
  YouTubeSpecifics$Outbound,
  YouTubeSpecifics
> = z.object({
  platform: z.literal("YOUTUBE"),
  privacy: z.optional(YouTubePrivacy$outboundSchema),
  category: z.optional(z.string()),
  tags: z.optional(z.array(z.string())),
  madeForKids: z.optional(z.boolean()),
});

export function youTubeSpecificsToJSON(
  youTubeSpecifics: YouTubeSpecifics,
): string {
  return JSON.stringify(
    YouTubeSpecifics$outboundSchema.parse(youTubeSpecifics),
  );
}
export function youTubeSpecificsFromJSON(
  jsonString: string,
): SafeParseResult<YouTubeSpecifics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => YouTubeSpecifics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'YouTubeSpecifics' from JSON`,
  );
}
