/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryStatus,
  DeliveryStatus$inboundSchema,
} from "./delivery-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostContentItem,
  PostContentItem$inboundSchema,
} from "./post-content-item.js";
import {
  YouTubePrivacy,
  YouTubePrivacy$inboundSchema,
} from "./you-tube-privacy.js";

export type YouTubePost = {
  platform: "YOUTUBE";
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Delivery lifecycle status for a post.
   *
   * @remarks
   *
   * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
   * `SENDING`: Delivery is currently in progress.
   * `SENT`: Delivery completed successfully.
   * `FAILED`: Delivery completed unsuccessfully.
   */
  deliveryStatus: DeliveryStatus;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is returned.
   */
  contentOverride?: Array<PostContentItem> | undefined;
  sentAt?: Date | undefined;
  externalPostId?: string | undefined;
  externalPostUrl?: string | undefined;
  errorMessage?: string | undefined;
  privacy?: YouTubePrivacy | undefined;
  category?: string | undefined;
  tags?: Array<string> | undefined;
  madeForKids?: boolean | undefined;
};

/** @internal */
export const YouTubePost$inboundSchema: z.ZodMiniType<YouTubePost, unknown> = z
  .object({
    platform: types.literal("YOUTUBE"),
    socialAccountId: types.string(),
    deliveryStatus: DeliveryStatus$inboundSchema,
    contentOverride: types.optional(z.array(PostContentItem$inboundSchema)),
    sentAt: types.optional(types.date()),
    externalPostId: types.optional(types.string()),
    externalPostUrl: types.optional(types.string()),
    errorMessage: types.optional(types.string()),
    privacy: types.optional(YouTubePrivacy$inboundSchema),
    category: types.optional(types.string()),
    tags: types.optional(z.array(types.string())),
    madeForKids: types.optional(types.boolean()),
  });

export function youTubePostFromJSON(
  jsonString: string,
): SafeParseResult<YouTubePost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => YouTubePost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'YouTubePost' from JSON`,
  );
}
