/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryStatus,
  DeliveryStatus$inboundSchema,
} from "./delivery-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostContentItem,
  PostContentItem$inboundSchema,
} from "./post-content-item.js";
import { PostSchedule, PostSchedule$inboundSchema } from "./post-schedule.js";
import {
  YouTubePrivacy,
  YouTubePrivacy$inboundSchema,
} from "./you-tube-privacy.js";

export type YouTubePost = {
  platform: "YOUTUBE";
  /**
   * Social account post identifier.
   */
  socialAccountPostId: string;
  /**
   * Parent post identifier.
   */
  postId: string;
  /**
   * Project identifier.
   */
  projectId: string;
  /**
   * Connected social account identifier.
   */
  socialAccountId: string;
  /**
   * Delivery lifecycle status for a post.
   *
   * @remarks
   *
   * `NOT_STARTED`: The post exists and is scheduled, but delivery has not started yet.
   * `SENDING`: Delivery is currently in progress.
   * `SENT`: Delivery completed successfully.
   * `FAILED`: Delivery completed unsuccessfully.
   */
  deliveryStatus: DeliveryStatus;
  /**
   * Post content expressed as thread items.
   *
   * @remarks
   *
   * The array exists for future thread support. Currently exactly one item
   * is returned.
   */
  content: Array<PostContentItem>;
  schedule: PostSchedule;
  /**
   * UTC time when the social account post was created.
   */
  createdAt: Date;
  /**
   * UTC time when the social account post was last updated.
   */
  updatedAt: Date;
  /**
   * UTC time when the latest delivery attempt for this social account post completed both for successful (`SENT`) and unsuccessful (`FAILED`) terminal `deliveryStatus` values.
   */
  deliveryCompletedAt?: Date | undefined;
  externalPostId?: string | undefined;
  externalPostUrl?: string | undefined;
  errorMessage?: string | undefined;
  privacy?: YouTubePrivacy | undefined;
  category?: string | undefined;
  tags?: Array<string> | undefined;
  madeForKids?: boolean | undefined;
};

/** @internal */
export const YouTubePost$inboundSchema: z.ZodMiniType<YouTubePost, unknown> = z
  .object({
    platform: types.literal("YOUTUBE"),
    socialAccountPostId: types.string(),
    postId: types.string(),
    projectId: types.string(),
    socialAccountId: types.string(),
    deliveryStatus: DeliveryStatus$inboundSchema,
    content: z.array(PostContentItem$inboundSchema),
    schedule: PostSchedule$inboundSchema,
    createdAt: types.date(),
    updatedAt: types.date(),
    deliveryCompletedAt: types.optional(types.date()),
    externalPostId: types.optional(types.string()),
    externalPostUrl: types.optional(types.string()),
    errorMessage: types.optional(types.string()),
    privacy: types.optional(YouTubePrivacy$inboundSchema),
    category: types.optional(types.string()),
    tags: types.optional(z.array(types.string())),
    madeForKids: types.optional(types.boolean()),
  });

export function youTubePostFromJSON(
  jsonString: string,
): SafeParseResult<YouTubePost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => YouTubePost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'YouTubePost' from JSON`,
  );
}
